gluster/glusterd2

volume/struct.go
volume/utils_misc.go

Updated the import path to the official github package as code.google.com is being shutdown.
Change-Id: I2c5f913a3aac3832c4b89fe574970c4a136ff4c1

Update import path for go-uuid

---

README.md
commands/command.go
commands/hello/hello.go
commands/volume-create/volume-create.go
commands/volume-delete/volume-delete.go
commands/volume-info/volume-info.go
commands/volume-list/volume-list.go
commands/volume-start/volume-start.go
commands/volume-stop/volume-stop.go
context/context.go
logging.go
main.go
rest/rest.go
store/volume.go
volgen/core.go
volgen/generate-graph.go
volume/volume_test.go
wercker.yml

Fix transfer issues

---

.gitignore
Makefile
glide.yaml
scripts/check-go.sh
scripts/check-reqs.sh
scripts/install-reqs.sh
wercker.yml

This makes it easier to do customized builds later.

Vendoring the dependent packages.

---

commands/volumes/volume-delete.go
volume/store-utils.go

fix volume delete workflow

---

utils/utils.go
utils/utils_test.go

While creating volume using glusterd2 it should support creation of
hirearchical directory stracture, if brick present in hierarchical
directory.
Issue #68
Signed-off-by: Gaurav Kumar Garg <garg.gaurav52@gmail.com>

Supporting hierarchical directory structure for bricks

---

context/context.go
etcdmgmt/etcd-mgmt.go
etcdmgmt/etcd-mgmt_test.go
main.go

Add tests for etcdmgmt

---

etcdmgmt/etcd-mgmt.go
etcdmgmt/etcd-mgmt_test.go
utils/utils.go
utils/utils_test.go

Add unit tests for utils and etcd-mgmt newly added functions

---

commands/peers/addpeer.go
context/context.go
context/myuuid.go
context/store.go
etcdmgmt/etcd-mgmt.go
main.go
peer/peer.go
peer/store-utils.go
rpc/client/peer-rpc-clnt.go
rpc/services/peer-rpc-svc.go
rpc/services/peer-svc.pb.go
rpc/services/peer-svc.proto
store/store.go

Adds the code flow for adding a proxy etcd node
Closes #84

etcd proxy configuration support

---

config/config.go

Set /var/lib/glusterd as default local state directory

---

glusterd.json.example
glusterd.yaml.example

Add YAML and JSON example configs

---

rest/utils.go

Fix for the follwing error in log:
ERRO[0035] Failed to send the response -<nil>
error=http: request method or response status code does not allow body

Don't include body for 204 responses

---

commands/peers/addpeer.go
errors/error.go

Fix crash caused on peer attaching local node

---

utils/utils.go

Use string matching before doing lookup

---

config.go

RpcPort is no longer used. Remove it.

---

Makefile

gometalinter has gained new tools which take longer to run.

Increase timeout for make verify

---

config.go
context/myuuid.go

Fix initialization of myUUIDFile

---

README.md
scripts/check-go.sh

With this change, glusterd-2.0's licensing will be compatible
with rest of gluster.
Signed-off-by: Vijay Bellur <vbellur@redhat.com>

README: Fix a minor typo and alter licensing scheme

---

Makefile

Set CAP_SYS_ADMIN on glusterd2 on `make install`

---

Makefile
gdctx/global.go
main.go
scripts/pkg-version
version.go

GD2 will start having periodic releases soon. This is step in that direction.

Prepare GD2 for releases

---

brick/brick.go
brick/port.go
commands/volumes/volume-create_test.go
commands/volumes/volume-start.go
commands/volumes/volume-stop.go
daemon/daemon.go
daemon/utils.go
errors/error.go
utils/utils.go
utils/volumeutils.go
volgen/core.go
volgen/generate-graph.go
volume/struct.go
volume/volume-utils.go

@kshlm Posted for some early feedback.

Daemon framework

---

volume/struct.go

Remove duplicates from nodes list

---

daemon/daemon.go
daemon/utils.go

Document daemon interface

---

config.go

Set workdir default value correctly

---

brick/brick.go

Since GD2 doesn't support volfile fetch yet, directly give bricks the
volfile path.

Use volfile path directly for brick

---

extras/test-env/build.sh
extras/test-env/hooks/post_push

- Fix build.sh to correctly check for DOCKER_TAG
- New tag matching regex for Docker hub
- Also tag built image latest
- Add post_push tag to push latest.

extras/test-env: More changes for autobuild

---

commands/peers/addpeer.go
commands/peers/peer-rpc-svc.go
rpc/server/listener.go
store/store.go

Fix some more golint warnings.

---

commands/peers/peer-rpc-svc.go
etcdmgmt/server.go
etcdmgmt/utils.go
main.go

Store etcd configs across glusterd restarts

---

transaction/context.go
transaction/transaction.go

Clean txn keys

---

commands/peers/deletepeer.go

Disallow deleting self peer

---

glide.lock

Update glide.lock to point to right libkv commit

---

scripts/build.sh

Set GO15VENDOREXPERIMENT to enable native vendor support

---

extras/test-env/setup.sh
scripts/check-reqs.sh
scripts/install-reqs.sh
utils/utils.go
utils/utils_test.go

Remove etcd binary as an external dependency

---

Makefile
scripts/build.sh
scripts/check-go.sh
wercker.yml

Bump up minimum go version required to 1.6

---

Makefile
etcdmgmt/server.go
scripts/lint-check.sh
transaction/context.go
transaction/context_mock.go
transaction/rpc-client.go
transaction/rpc-service.go

Fix golint warnings and enforce check

---

config.go
etcdmgmt/client.go
etcdmgmt/utils.go
main.go
store/store.go

Make etcd interfaces configurable

---

brick/volfile-template.go
volgen/core.go

Simplify brick volfile generation using template

---

brick/brick.go
daemon/daemon.go
main.go
utils/utils.go

* Create dirs required by brick processes
* Update brick start args
* Wait a little before checking if daemon is up
Closes #150

Fix starting of bricks

---

peer/store-utils.go
utils/peerutils.go

* Allow addresses without ports during add peer operation
* Normalize peer address before comparison

Fully support addresses without ports

---

brick/volfile-template.go
commands/volumes/volume-create.go
commands/volumes/volume-create_test.go
volgen/core.go
volume/struct.go

* Generate brick volfiles only on nodes that contain those bricks
* Generate trusted username and password in brick volfiles

Selectively generate brick volfiles and also include auth credentials

---

glide.lock
glide.yaml

Update libkv commit in glide.yaml

---

volgen/core.go

Fix incorrect client volfile when volume has single brick

---

commands/peers/peer-rpc-svc.go
etcdmgmt/server.go
gdctx/global.go
gdctx/myuuid.go
main.go
servers/sunrpc/program.go

Mostly stylistic cleanups, no functional change.

Main() cleanup

---

commands/volumes/volume-start.go

Workaround to always detect address already in use case

---

glide.lock
servers/sunrpc/program.go
servers/sunrpc/server.go

Move Program interface to sunrpc package

---

brick/types.go
commands/volumes/volume-status.go
pmap/pmap.go
pmap/rpc_prog.go

Closes issue https://github.com/gluster/glusterd2/issues/212
Signed-off-by: Samikshan Bairagya <samikshan@gmail.com>

Get brick process status in response to volume status call

---

commands/peers/commands.go
commands/peers/peer-status.go
etcdmgmt/client.go

Implement /etcdstatus and /etcdhealth endpoints

---

doc/coding.md

doc: Write simple doc on coding conventions

---

config.go
etcdmgmt/logging.go
etcdmgmt/server.go

Make embedded etcd log to a file

---

commands/volumes/volume-status.go

Fix nil pointer dereference in volumeStatusHandler()

---

volgen/brick-template.go
volgen/core.go

Add missing xlators in default brick graph

---

logging.go

Problem:
Log entries by go's built-in 'log' package were being logged into the etcd
log file as it was hijacked by etcd's 'capnslog'.
This small change will set logrus as output for entries done by 'log'
package.

Redirect standard logs to logrus

---

brick/glusterfsd.go
brick/rpc_prog_clnt.go
brick/rpc_prog_types.go
commands/volumes/volume-stop.go
daemon/connection.go
daemon/daemon.go
glide.lock
servers/sunrpc/program.go

...with volume stop as an example.
Closes #240 

Implement glusterd2 to brick communication

---

doc/coding.md
doc/network.md
pmap/pmap.go
servers/sunrpc/callback.go
servers/sunrpc/dump_prog.go
servers/sunrpc/server.go

...and update few coding guidelines about error handling
and remove some old TODO comments that are no longer
relevant.
Closes #100, closes #104 

doc: Add document for servers and ports used

---

brick/types.go
commands/volumes/volume-create.go
commands/volumes/volume-create_test.go
commands/volumes/volume-delete.go
utils/volumeutils.go
volgen/core.go
volume/struct.go
volume/volume_test.go

...needed for upcoming work on add and remove brick so that
volgen code can be reused there.
This PR introduces no functional change.

Refactor volgen and cleanup vol create/delete

---

commands/volumes/brickutils.go
commands/volumes/commands.go
commands/volumes/volume-create.go
commands/volumes/volume-delete.go
commands/volumes/volume-expand.go
commands/volumes/volume-start.go
servers/sunrpc/callback.go
volgen/core.go
volume/struct.go

Limited to currently supported volume types i.e distribute, replicate and distributed replicate
Updates issue #267

Implement volume expand (add brick)

---

e2e/peer_ops_test.go
e2e/utils_test.go
e2e/volume_ops_test.go

I assumed assert() will exit the test, but it's require() that exits
the test being run when the condition being tested is false.

Fix panics during functest

---

main.go
xlator/global.go
xlator/options.go
xlator/options.h
xlator/xlator.go

Load xlator options from their shared objects

---

glide.lock
glide.yaml
store/remote.go
store/store.go

Allow connecting to local etcd instance and bump etcd version

---

e2e/peer_ops_test.go
e2e/restart_test.go
e2e/utils_test.go
pkg/elasticetcd/server.go

elasticetcd: Preserve etcd data when restarting 1-node cluster

---

commands/volumes/commands.go
commands/volumes/common.go
commands/volumes/volume-create.go
commands/volumes/volume-expand.go
commands/volumes/volume-option.go
peer/store-utils.go

...and allow setting volume options during volume create as well

Add volume set API

---

.gitignore
e2e/peer_ops_test.go
e2e/restart_test.go
e2e/utils_test.go
e2e/volume_ops_test.go
pkg/api/errors.go
pkg/api/req.go
pkg/api/resp.go
pkg/restclient/common.go
pkg/restclient/errors.go
pkg/restclient/examples/main.go
pkg/restclient/peer.go
pkg/restclient/volume.go

REST Client for Glusterd2 APIs. Initially these APIs will be used by
CLI project, it can be used by any application which is written in Go
lang.
Example:
package main
import (
"fmt"
"github.com/gluster/glusterd2/pkg/restclient"
)
func main(){
client := restclient.NewRESTClient("http://localhost:24007", "", "")
err := client.VolumeStart("gv1")
if err != nil{
fmt.Println("Failed to Start Volume gv1")
} else{
fmt.Println("Started Volume gv1 successfully")
}
}
Signed-off-by: Aravinda VK mail@aravindavk.in
Updates: #265

restclient: Golang REST Client library

---

.gitignore
Makefile
cli/cmd/common.go
cli/cmd/peer.go
cli/cmd/root.go
cli/cmd/volume.go
cli/main.go
cli/oldfmt.go
glide.lock
glide.yaml
scripts/build-cli.sh

Updates: #205
Signed-off-by: Aravinda VK <mail@aravindavk.in>

cli: Initial patch for Glusterd2 CLI

---

README.md
doc/development-guide.md
doc/quick-start-user-guide.md

doc: Add quick start user guide and development guide

---

scripts/new-gd2-plugin.py

plugins: A tool to bootstrap plugin code

---

cli/cmd/volume.go

Hello @aravindavk
I added the volume deletion option for the gd2 CLI, can you please review the same.
Opened this new PR, since force pushed in the earlier PR(sorry!)
Thanks.

cli: Add volume delete option for CLI.

---

glide.lock
glide.yaml
middleware/recover.go
middleware/request_logging.go
servers/rest/rest.go

log: Associate reqid with client request logs

---

cli/cmd/common.go
cli/cmd/volume.go
pkg/restclient/volume.go

CLI: Volume set option for gd2 cli

---

cli/cmd/volume.go
commands/volumes/volume-list.go
e2e/restart_test.go
pkg/api/req.go
pkg/restclient/volume.go

Updates #205 
More discussion on the same is on PR #369 
@aravindavk can you please review the same. Thanks.

cli: Volume List and Volume Info options to display the respective info

---

config.go
gdctx/global.go
main.go
middleware/expvar.go
pmap/pmap.go
servers/rest/rest.go
servers/sunrpc/server.go
transaction/transaction.go
utils/statedump.go
version/version.go

Add /statedump endpoint for metrics

---

config.go
doc/quick-start-user-guide.md
main.go
volgen/static.go
volgen/template.go
xlator/global.go

Auto-generate default templates and gracefully handle loading xlators

---

extras/rpms/glusterd2.spec
extras/rpms/glusterd2.toml

I should be using make install to install in specfile, but can't get it
to work as I expected right now.

extras/rpms: Update specfile to support templates

---

cli/cmd/volume.go
commands/volumes/volume-create.go
commands/volumes/volume-create_test.go
commands/volumes/volume-expand.go
pkg/api/req.go
pkg/restclient/volume.go

Updates #205: Add volume expand option to expand a Gluster Volume
by adding more bricks.

CLI: Volume Expand option for gd2 CLI

---

e2e/volume_ops_test.go

Signed-off-by: Kamal Mohanan <kmohanan@redhat.com>

e2e: Add test for volume expand operation.

---

extras/rpms/glusterd2.spec
scripts/dist.sh

Also, remove `set -x` from dist.sh

Fix specfile

---

commands/peers/addpeer.go
commands/peers/deletepeer.go
commands/peers/getpeer.go
commands/peers/getpeers.go
commands/peers/peer-status.go
commands/volumes/volume-create.go
commands/volumes/volume-delete.go
commands/volumes/volume-expand.go
commands/volumes/volume-info.go
commands/volumes/volume-list.go
commands/volumes/volume-option.go
commands/volumes/volume-start.go
commands/volumes/volume-status.go
commands/volumes/volume-stop.go
pkg/api/errors.go
plugins/georeplication/rest.go
servers/rest/utils/utils.go

Added extra argument to SendHTTPError function and added default error
code in all places.
To add a new error code, add entry in `pkg/api/errors.go` and then use
while calling SendHTTPError
Updates: #419
Signed-off-by: Aravinda VK <mail@aravindavk.in>

Added error code argument to SendHTTPError

---

cli/cmd/common.go
cli/cmd/root.go
cli/main.go

Signed-off-by: Kamal Mohanan <kmohanan@redhat.com>

cli: Make log file and log level configurable via CLI options.

---

cli/cmd/common.go
cli/cmd/peer.go
cli/cmd/volume.go

cli: Use cobra's in-built validation for number of positional args

---

scripts/new-gd2-plugin.py

Fix plugin initial template generator after code refactor

---

glusterd2/volgen/static.go
glusterd2/volgen/templates/replicate.graph

Adding template for replicate graph to allow creation of pure
replicate volumes.
Fixes: #453
Signed-off-by: karthik-us <ksubrahm@redhat.com>

volgen: Adding replicate.graph template

---

Gopkg.lock
Gopkg.toml
glustercli/cmd/root.go
glusterd2/commands/peers/peer-rpc-svc.go
glusterd2/main.go
glusterd2/middleware/request_logging.go
glusterd2/servers/rest/utils/utils.go
pkg/logging/hook.go
pkg/logging/logging.go

Log file name, function name and line number

---

glusterd2/xlator/options/options.go

WIP: Add validation functions for the available option types.

---

Gopkg.lock
Gopkg.toml

...left out when PR 436 was merged.

Add missing govalidator dependency

---

glusterd2/commands/volumes/volume-start.go

Fix crash during txn failure in volume start

---

glustercli/cmd/volume.go

This Patch adds gluster volume status to cli. It
takes volume-name as optional argument. If volume
name not provided the volume status for all the
volumes will be displayed.
Issue: https://github.com/gluster/glusterd2/issues/488
Signed-off-by: Darshan N <darshan.n.2024@gmail.com>

Adds "gluster volume status" to CLI

---

e2e/utils_test.go
glusterd2/servers/sunrpc/server.go

Serve RPCs over Unix domain socket

---

glusterd2/xlator/options/options.go

Updates #404: Add validations for Internet Address.

---

glusterd2/xlator/global.go

Remove warning/hint to use experimental branch

---

glusterd2/xlator/load.go
glusterd2/xlator/xlator.go
glusterd2/xlator/xlator.h

Currently, it's only server xlator which does so.
Ref: https://review.gluster.org/18879
Closes #470 

Add support loading xlators exposing xlator_api

---

plugins/georeplication/api/resp.go
plugins/georeplication/gsyncd.go
plugins/georeplication/init.go
plugins/georeplication/rest.go
plugins/georeplication/transactions.go

plugin/geo-rep: Status command implementation

---

doc/quick-start-user-guide.md

...and use the same IP in examples.

doc: Update usage of master branch

---

glusterd2/xlator/options/options.go

Updates #404: Add validations for Size.

---

glusterd2/xlator/options/options.go

Validating if the "address"
* is (anonymous) OR
* is valid FQDN or valid IPv4/6 address OR
* contains wildcard chars e.g.'*' or '#' or '?' or '^'
* is valid ipv4 subnet pattern (xx.xx.xx.xx/n)

Updates #404: Add validations for Client Auth Address.

---

e2e/volume_ops_test.go
glusterd2/commands/volumes/volume-create.go
glusterd2/volgen/cluster-graph.go
glusterd2/volgen/static.go
glusterd2/volgen/templates/disperse.graph
glusterd2/volume/struct.go
pkg/api/volume_req.go

Signed-off-by: Kamal Mohanan <kmohanan@redhat.com>

Disperse volume support

---

glusterd2/servers/sunrpc/dict.go
glusterd2/servers/sunrpc/handshake_prog.go

And also:
* Fix serialization of glusterfs dicts
* Fix hang in fetching invalid volfile
Closes #518

 Implement GF_HNDSK_GET_VOLUME_INFO procedure call

---

glusterd2/plugin/plugins.go
glusterd2/volgen2/volfile_bitd.go
glusterd2/volgen2/volfile_scrub.go
glusterd2/volume/struct.go
pkg/errors/error.go
plugins/bitrot/bitd.go
plugins/bitrot/init.go
plugins/bitrot/rest.go
plugins/bitrot/scrubd.go
plugins/bitrot/transactions.go

This patch adds following support
1. Enable bitrot : Starts bitd and scrubber
2. Disable bitrot: Stops bitd and scrubber

bitrot: Add bitrot plugin to glusterd2

---

glusterd2/commands/volumes/common.go
glusterd2/commands/volumes/volume-create.go
glusterd2/commands/volumes/volume-option.go
glusterd2/xlator/global.go
glusterd2/xlator/validation.go
glusterd2/xlator/xlator.go

Signed-off-by: Kamal Mohanan <kmohanan@redhat.com>

Add support for validator functions of volume options

---

glusterd2/plugin/plugins.go
plugins/quota/api/req.go
plugins/quota/api/resp.go
plugins/quota/init.go
plugins/quota/rest.go

Initial plugin with stubs required for quota.
Sending this so as to divide development task
and code in parallel.
Updates: #421
Signed-off-by: Sanoj Unnikrishnan <sunnikri@redhat.com>

quota plugin stubs

---

e2e/georep_test.go
plugins/georeplication/api/req.go
plugins/georeplication/api/resp.go
plugins/georeplication/gsyncd.go
plugins/georeplication/init.go
plugins/georeplication/rest.go
plugins/georeplication/transactions.go

Implemented APIs for Config Get, Set and Reset commands
Also added Config file generation before gsyncd start
Updates: #271

geo-rep: Config management

---

glusterd2/store/store.go

When remote etcd store is used instead of embedded etcd, the old namespace used
by peer before joining the cluster wasn't being cleaned up earlier.
All the keys in the old namespace is now deleted.

store: Cleanup old namespace in remote store

---

glusterd2/commands/peers/addpeer.go
glusterd2/commands/peers/deletepeer.go
glusterd2/commands/peers/events.go
glusterd2/config.go
glusterd2/events/events.go
glusterd2/events/logger.go
pkg/logging/logging.go

* Log events to a separate logfile in JSON format (so that it's parse-able).
* Emit events for peer add and peer remove
* Set timestamp and origin node ID in emitted events

events: Log events to file and add peer events

---

Makefile

Use like:
make DEPENV=http_proxy=...

Setup dep usage in make to allow env, like proxy settings

---

glusterd2/volume/struct.go
pkg/api/bitrot_resp.go
plugins/bitrot/init.go
plugins/bitrot/rest.go
plugins/bitrot/transactions.go

bitrot: Add scrub status support

---

e2e/georep_test.go
glustercli/cmd/georep.go
pkg/restclient/georep.go
plugins/georeplication/api/req.go
plugins/georeplication/api/resp.go
plugins/georeplication/gsyncd.go
plugins/georeplication/init.go
plugins/georeplication/rest.go
plugins/georeplication/store-utils.go
plugins/georeplication/transactions.go

Create/Start/Pause/Resume/Stop/Delete

cli: Geo-replication CLI

---

Gopkg.lock
Gopkg.toml
glusterd2/brick/brick_rpc_prog.go
glusterd2/daemon/connection.go
glusterd2/plugin/common.go
glusterd2/pmap/rpc_prog.go
glusterd2/servers/sunrpc/callback.go
glusterd2/servers/sunrpc/dump_prog.go
glusterd2/servers/sunrpc/handshake_prog.go
glusterd2/servers/sunrpc/program.go
glusterd2/servers/sunrpc/server.go
pkg/sunrpc/clientcodec.go
pkg/sunrpc/cmux_matcher.go
pkg/sunrpc/errors.go
pkg/sunrpc/message_types.go
pkg/sunrpc/portmapper.go
pkg/sunrpc/procedure_registry.go
pkg/sunrpc/program_types.go
pkg/sunrpc/record.go
pkg/sunrpc/servercodec.go
plugins/bitrot/init.go
plugins/events/init.go
plugins/georeplication/init.go
plugins/glustershd/init.go
plugins/hello/init.go
plugins/quota/init.go
scripts/new-gd2-plugin.py

This is an as-is import of sunrpc codec without introducing any
functional code changes. There are few opportunities for cleanup and
optimizations and that'll be done in future.

Import sunrpc into pkg

---

Gopkg.lock
Gopkg.toml
glusterd2/servers/muxsrv/server.go
glusterd2/servers/rest/rest.go
glusterd2/servers/sunrpc/server.go
pkg/tlsmatcher/matcher.go
pkg/tlsmatcher/matcher_test.go

This is part of the attempt to consolidate our dependencies.

Switch to github.com/cockroachdb/cmux

---

plugins/georeplication/rest.go
plugins/georeplication/transactions.go

geo-replication: Error handling and same Volume ID validation

---

glustercli/cmd/events.go
pkg/restclient/events.go

cli: Events API CLI support for managing Webhooks

---

glusterd2/servers/eventlistener/handler.go
glusterd2/servers/eventlistener/server.go

Listen on UDP port 24007 for incoming events

---

glustercli/cmd/events.go
glusterd2/commands/global/setglobaloptions.go
glusterd2/commands/volumes/optiongroup-create.go
glusterd2/events/global.go
glusterd2/events/nfs-ganesha.go
glusterd2/xlator/validation.go
pkg/sunrpc/clientcodec.go

Many were found by the goreportcard service:
https://goreportcard.com/report/github.com/gluster/glusterd2
We should make some of those tests part of our CI.

Fix minor lint and logging issues

---

e2e/volume_ops_test.go
glustercli/cmd/volume.go
glusterd2/brick/types.go
glusterd2/brick/validation.go
glusterd2/commands/volumes/common.go
glusterd2/commands/volumes/volume-create.go
glusterd2/commands/volumes/volume-create_test.go
glusterd2/commands/volumes/volume-delete.go
glusterd2/commands/volumes/volume-expand.go
glusterd2/servers/servers.go
glusterd2/transaction/context.go
glusterd2/volume/struct.go
pkg/api/volume_req.go
pkg/utils/utils.go
pkg/utils/utils_test.go

* Separated brick validation step from the step which modified brick path by setting xattrs.
* Added rollback functions to volume create.
* Add `Force` field to add-brick API.
* Granularize brick validation checks.

 volume-create: Fix few outstanding issues

---

glusterd2/xlator/load.go
glusterd2/xlator/options/options.go
glusterd2/xlator/options/options.h
version/version.go

Also, update version to v4.1dev, as we now have a release-4.0 branch.

Update the Options struct to include OptionLevel

---

e2e/volume_ops_test.go
glusterd2/brick/glusterfsd.go
glusterd2/brick/types.go
glusterd2/commands/volumes/bricks-status.go
glusterd2/commands/volumes/brickutils.go
glusterd2/commands/volumes/utils.go
glusterd2/commands/volumes/volume-create.go
glusterd2/commands/volumes/volume-expand.go
glusterd2/commands/volumes/volume-info.go
glusterd2/commands/volumes/volume-start.go
glusterd2/commands/volumes/volume-status.go
glusterd2/volume/fs_utils.go
glusterd2/volume/struct.go
glusterd2/volume/volume-utils.go
glusterd2/xlator/validation.go
pkg/utils/types.go
pkg/utils/volumeutils.go

This patch is required for supporting snapshot integration as snapshot has a dependency on volinfo and similiar functions that handles it

glusterd2: Refactoring of functions for snapshot

---

extras/rpms/glusterd2-logrotate
extras/rpms/glusterd2.spec

- Add logrotate configuration
- Correct BuildRequires on go_compiler
- Require glusterfs-server < 4.1.0
- Add correct changelog for spec

Updates to specfile

---

extras/centos-ci.sh
extras/rpms/glusterd2-logrotate
extras/rpms/glusterd2.spec

Backport of #601 changes to specfile from master.

Update specfile 4.0 and centos-ci

---

e2e/volume_ops_test.go
glusterd2/commands/volumes/common.go
glusterd2/xlator/load.go
glusterd2/xlator/options/options.go

Enforce IsSettable flag of xlator options

---

doc/coding.md
doc/development-guide.md
doc/xlator.md

...with some useful information.
It's also easier to point code contributors to this page during reviews instead of repeating it each time.

Update development guide and coding guidelines

---

glusterd2/config.go
glusterd2/main.go

Custom pidfile can be specified using,
glusterd2 --pidfile=<path>
Fixes: #627

Added support for pid file

---

pkg/restclient/errors.go

Include error message in restclient response

---

glusterd2/main.go

...now that we have moved to using volgen2

Do not auto-generate template files

---

glusterd2/config.go
glusterd2/events/events.go
glusterd2/events/hooks.go
glusterd2/main.go

Add support for post hook scripts

---

e2e/volume_ops_test.go
glusterd2/xlator/load.go

Dependent change:
https://review.gluster.org/#/c/19905

Use `glusterfsd --print-xlatordir`

---

.gitignore

If your're using vi, this is convenient...

gitignore: ignore vi backup files

---

scripts/install-reqs.sh

...as against installing from source and polluting the machine's
$GOPATH/src

gometalinter: Install released binary package

---

glustercli/cmd/volume-create.go

cli: Add thin arbiter support

---

glusterd2/volgen2/clustergraph.go

volgen: Add support for Thin Arbiter Volfile

---

glustercli/cmd/bitrot.go
glustercli/cmd/common.go
glustercli/cmd/events.go
glustercli/cmd/georep.go
glustercli/cmd/peer.go
glustercli/cmd/root.go
glustercli/cmd/volume-create.go
glustercli/cmd/volume-set.go
glustercli/cmd/volume.go

log error message to stdout
fix for #629  

add verbose flag to cli to

---

glusterd2/xlator/global.go
glusterd2/xlator/validation.go
plugins/afr/validate.go
plugins/dht/validate.go

Move afr and dht validations out of core

---

glusterd2/transaction/step.go

txn: Fix error response being lost/ignored

---

glusterd2/gdctx/context_test.go
glusterd2/gdctx/global_test.go
glusterd2/gdctx/id_test.go
glusterd2/middleware/auth_test.go
glusterd2/middleware/recover_test.go
glusterd2/middleware/request_id_test.go
glusterd2/middleware/request_logging_test.go
glusterd2/pmap/pmap_test.go
glusterd2/pmap/rpc_prog_test.go
glusterd2/volgen/cluster-graph_test.go
glusterd2/volgen/config_test.go
glusterd2/volgen/errors_test.go
glusterd2/volgen/template_test.go
glusterd2/volgen/volfile_test.go

unit test cases for gdctx, middleware,pmap and volgen packages

glusterd2 unit test cases for gdctx,middleware, pmap and volgen

---

glustercli/cmd/georep.go
glustercli/cmd/volume.go

cli: Add length checks to prevent index errors

---

glustercli/cmd/volume.go

Also changed the Volume info output Field State to Status

cli: Display Hostname instead of Peer ID in Volume info

---

e2e/peer_ops_test.go
glustercli/cmd/peer.go
pkg/restclient/peer.go

peer detach with default port if the port is not provided in peer detach CLI command

peer detach with default port 

---

doc/development-guide.md

providing etcd endpoints inside [] fails with error 
Error: dial tcp: address [127.0.0.1:2379]: missing port in address

pass etcd endpoints within " "

---

doc/quick-start-user-guide.md

updated volume create request in the user guide.

change nodeid to peerid in volume create request

---

glustercli/cmd/peer.go
glustercli/cmd/utils.go

Add Online field to pool list output

---

glustercli/cmd/volume.go

display volume options in CLI

---

doc/quick-start-user-guide.md
e2e/peer_ops_test.go
glustercli/cmd/peer.go
glusterd2/servers/eventlistener/eventtypes.go
pkg/restclient/peer.go

updated peer commands in glustercli 
Closes #743

updated peer commands

---

doc/endpoints.md
glustercli/cmd/volume.go
glusterd2/commands/volumes/commands.go
glusterd2/commands/volumes/volfiles.go
glusterd2/volgen2/store-utils.go
pkg/errors/error.go

Added ability to fetch individual volfiles from their volfile ID

---

glusterd2/commands/volumes/volume-create-txn.go
glusterd2/commands/volumes/volume-expand-txn.go
glusterd2/commands/volumes/volume-option.go
glusterd2/config.go
pkg/utils/peerutils_test.go

Fix golint and ineffassign issues

---

glustercli/cmd/bitrot.go

bitrot: set advanced flag to bitrot volume options

---

e2e/volume_ops_test.go
glusterd2/commands/volumes/volume-create.go
pkg/errors/error.go

It is necessary to validate volume name before volume creation.
Fixes #772 

validate volume name

---

doc/endpoints.md
e2e/glustershd_test.go
e2e/quota_enable.go
e2e/volume_ops_test.go
glustercli/cmd/volume.go
glusterd2/commands/volumes/commands.go
glusterd2/commands/volumes/volume-start.go
pkg/api/volume_req.go
pkg/api/volume_resp.go
pkg/restclient/volume.go

added requestbody for volume start api

---

pkg/api/volume_resp.go

Resolve Comments on issue [#462](https://github.com/gluster/glusterd2/issues/462#issuecomment-391221151)
Closes #462

resolve documentation issue for volumeGetResp and volumeListResp

---

glustercli/cmd/device.go
pkg/restclient/device.go
plugins/device/rest.go
plugins/device/store-utils.go

Also fixed issues during device add(Json Marshal error and store error
for first time)
Updates: #728

cli: Added CLI for Device Add

---

glusterd2/commands/peers/peer-rpc-svc.go
glusterd2/transaction/rpc-client.go
glusterd2/transaction/rpc-service.go

This reverts commit 5c0eaeaabe517f22276f2b03c2a1ed77e189f4ae.
Closes #792

Revert "Use the built-in "context" package"

---

e2e/peer_ops_test.go
glustercli/cmd/peer.go
glusterd2/commands/peers/getpeers.go
glusterd2/peer/store-utils.go
pkg/restclient/peer.go

@prashanthpai Please review. Resolves formatting issue commented in https://github.com/gluster/glusterd2/pull/790

Formatting go code

---

glusterd2/config.go

set defaultpeerport as part of setting default configuration

---

glusterd2/transaction/lock.go
glusterd2/transaction/transaction.go

... so that PRs already present can be merged.
@prashanthpai /@aravindavk please merge this so that the PRs in progress
(rebalance,snapshot, IVC) can get merged easily.  Once the PRs are in, I'll
update them personally to the new functions.

Add back the old transaction/lock functions

---

glustercli/cmd/volume-create.go

add volume create command to glustercli

---

glustercli/cmd/volume-create.go

added missed experimental and deprecated flags

---

glusterd2/plugin/plugins.go
glusterd2/servers/sunrpc/handshake_prog.go
plugins/rebalance/api/req_resp.go
plugins/rebalance/errors.go
plugins/rebalance/eventnotify.go
plugins/rebalance/init.go
plugins/rebalance/process.go
plugins/rebalance/rest.go
plugins/rebalance/transaction.go
plugins/rebalance/utils.go

Rebalance plugin (part 1) implements:
- rebalance start (with fix-layout and force options)
- rebalance stop
- rebalance status
Adding Akarsha who did the bulk of the work as the author.
Author: Akarsha Rai <akrai@redhat.com>
Signed-off-by: N Balachandran <nbalacha@redhat.com>

GD2/rebalance: Rebalance plugin

---

plugins/bitrot/rest.go

corrected bitrot enabled check  on volume info for bitrot scrub status
Fixes: #798 

corrected bitrot enabled check  on

---

glustercli/cmd/volume.go

updated printing brick counter logic for displaying volume info

updated printing brick counter logic for displaying volume info

---

glusterd2/transaction/step.go

This will retain the old behaviour of reporting last error received
in a transaction to the client.

txn: Fix last error response regression

---

glusterd2/volgen2/clustergraph.go
glusterd2/volume/struct.go

volgen: Fix bitrot volgen issue when no local bricks in a subvolume

---

glusterd2/commands/volumes/volume-list.go

Initialize VolumeListResp to avoid null response in HTTP

---

glustercli/cmd/peer.go

allow only peerID as input for peer removal in glustercli

---

glusterd2/commands/volumes/volume-create-txn.go

Set Arbiter count option on Arbiter Volume creation

---

glusterd2/commands/peers/getpeers.go

return internal server error in case  of get from store fails

---

glusterd2/cluster/store-utils.go
glusterd2/commands/peers/addpeer.go
glusterd2/commands/snapshot/snapshot-create.go
glusterd2/commands/snapshot/snapshot-list.go
glusterd2/commands/volumes/common.go
glusterd2/commands/volumes/optiongroup-create.go
glusterd2/commands/volumes/optiongroup-delete.go
glusterd2/commands/volumes/optiongroup-list.go
glusterd2/commands/volumes/volume-list.go
glusterd2/commands/volumes/volume-reset.go
glusterd2/daemon/store.go
glusterd2/events/global.go
glusterd2/peer/store-utils.go
glusterd2/servers/sunrpc/handshake_prog.go
glusterd2/snapshot/store-utils.go
glusterd2/store/liveness.go
glusterd2/store/store.go
glusterd2/transaction/context.go
glusterd2/transaction/transaction.go
glusterd2/volgen/volgen.go
glusterd2/volgen2/store-utils.go
glusterd2/volume/store-utils.go
plugins/events/store-utils.go
plugins/georeplication/rest.go
plugins/georeplication/store-utils.go
plugins/rebalance/rest.go
plugins/rebalance/utils.go

added wrapper functions for store operations

---

glusterd2/commands/volumes/optiongroup-delete.go
glusterd2/commands/volumes/volume-delete.go
pkg/restclient/events.go
pkg/restclient/georep.go
pkg/restclient/volume.go
plugins/events/rest.go
plugins/georeplication/rest.go

return 204 HTTP StatusNocontent for delete operations

---

glusterd2/gdctx/global.go

store token, if auth file already present

---

glustercli/cmd/common.go
glustercli/cmd/root.go

added support for JWT token authentication in glustercli

---

pkg/restclient/device.go
plugins/device/rest.go

return HTTP StatusCreated instead on StatusOK for adding device

---

pkg/restclient/bitrot.go

updated function comment in rest api for get bitrot scrub status

---

glusterd2/commands/peers/editpeer.go
glusterd2/commands/snapshot/snapshot-activate.go
glusterd2/commands/snapshot/snapshot-create.go
glusterd2/commands/snapshot/snapshot-deactivate.go
glusterd2/commands/volumes/bricks-status.go
glusterd2/commands/volumes/volfiles.go
glusterd2/commands/volumes/volume-create.go
glusterd2/commands/volumes/volume-delete.go
glusterd2/commands/volumes/volume-edit.go
glusterd2/commands/volumes/volume-expand.go
glusterd2/commands/volumes/volume-info.go
glusterd2/commands/volumes/volume-option.go
glusterd2/commands/volumes/volume-reset.go
glusterd2/commands/volumes/volume-start.go
glusterd2/commands/volumes/volume-statedump.go
glusterd2/commands/volumes/volume-status.go
glusterd2/commands/volumes/volume-stop.go
glusterd2/servers/rest/utils/utils.go
glusterd2/volgen2/store-utils.go
pkg/errors/error.go
plugins/bitrot/rest.go
plugins/device/rest.go
plugins/georeplication/rest.go
plugins/glustershd/rest.go
plugins/quota/rest.go
plugins/rebalance/rest.go
plugins/smartvol/rest.go

code cleanup , added function to return HTTP status code based on error

---

glustercli/cmd/volume.go

added volume size  command to glustercli

---

glusterd2/brick/glusterfsd.go
glusterd2/commands/snapshot/snapshot-activate.go
glusterd2/commands/snapshot/snapshot-deactivate.go
glusterd2/commands/volumes/volume-expand-txn.go
glusterd2/commands/volumes/volume-option.go
glusterd2/commands/volumes/volume-start.go
glusterd2/commands/volumes/volume-statedump.go
glusterd2/commands/volumes/volume-stop.go
glusterd2/daemon/daemon.go
glusterd2/main.go
glusterd2/snapshot/snapshot-utils.go
glusterd2/xlator/actors.go
plugins/bitrot/transactions.go
plugins/georeplication/transactions.go
plugins/glustershd/actor.go
plugins/quota/rest.go
plugins/rebalance/transaction.go

Log with request ID and transaction ID in daemon framework

---

glusterd2/gdctx/global.go

use crypto for generating security-sensitive data.

use crypto/rand for generating random secret

---

plugins/glustershd/actor.go

Resolve process already running error with SHD

Resolve process already running error with SHD

---

e2e/peer_ops_test.go
pkg/restclient/peer.go

Peers: added get peer info api in rest client

---

doc/xlator.md
glusterd2/servers/eventlistener/handler.go
glusterd2/store/liveness.go
glusterd2/transaction/context.go
glusterd2/transaction/context_mock.go
glusterd2/volgen/volgen.go
glusterd2/volgen2/clustergraph.go
glusterd2/volgen2/generate.go
glusterd2/volgen2/volfile_bitd.go
glusterd2/volgen2/volfile_brick.go
glusterd2/volgen2/volfile_fuse.go
glusterd2/volgen2/volfile_gfproxy.go
glusterd2/volgen2/volfile_quotad.go
glusterd2/volgen2/volfile_rebalance.go
glusterd2/volgen2/volfile_scrub.go
glusterd2/volgen2/volfile_shd.go
plugins/georeplication/api/resp.go
plugins/rebalance/api/req_resp.go
plugins/rebalance/eventnotify.go
plugins/rebalance/transaction.go

Issue: https://github.com/gluster/glusterd2/issues/576

Using peerid instead of nodeid

---

e2e/bitrot_test.go
e2e/georep_test.go
e2e/glustershd_test.go
e2e/peer_ops_test.go
e2e/quota_enable.go
e2e/restart_test.go
e2e/smartvol_ops_test.go
e2e/utils_test.go
e2e/volume_ops_test.go

use testcase Name as volume name  in e2e test cases

---

glusterd2/commands/volumes/volume-create-txn.go

Initialize slice to avoid null  in HTTP response

---

doc/testing.md

doc: Illustrate running single functional test

---

plugins/device/api/req.go
plugins/device/deviceutils/store-utils.go
plugins/device/init.go
plugins/device/rest.go

https://github.com/gluster/glusterd2/issues/728

Editing status of device (Enabling/Disabling)

---

e2e/utils_test.go

Also:
* Make setupCluster() use the restclient to do peer operations
* Bump up default wait time to check if gd2 is alive from 1.5s to 2s
* Ensure cleanup happens in all failure cases
Closes #956 

e2e: Ensure setupCluster() returns error on failure

---

Makefile
e2e/bitrot_test.go
e2e/config/1.toml
e2e/config/2.toml
e2e/config/3.toml
e2e/config/4.toml
e2e/georep_test.go
e2e/glustershd_test.go
e2e/peer_ops_test.go
e2e/quota_enable.go
e2e/restart_test.go
e2e/smartvol_ops_test.go
e2e/utils_test.go
e2e/volume_ops_test.go
e2e/webhook_test.go
glustercli/cmd/root.go
glusterd2.toml.example
glusterd2/gdctx/global.go
scripts/build.sh
scripts/gen-gd2conf.sh

* Enable Rest authentication in glusterd2 by default
* updated test cases to use auth by default
* Protect Auth file to "gluster" group only
Fixes: #606 

 Enable Rest Authentication by default

---

glusterd2/commands/peers/deletepeer.go

Custom error message when peer remove fails because peer does not exists

---

doc/coding.md

Add some opinions and conventions about:
* logging of txn.* methods
* logging using WithError()
* use of goto statements
* add links pointing to go proverbs and good commit messages
* reusing txn step function in multiple transactions

doc: Update coding convention with new information

---

glusterd2/commands/peers/deletepeer.go

If Peer is not alive then sending a delete request for that peer will delete
Peer details from the store But Peer will fail to leave the cluster, Because
rpc call fails.
Before Deleting We should check whether peer is alive or not.
Fixes #1108

Delete peer details from store after peer leaves cluster

---

glusterd2/commands/snapshot/snapshot-activate.go
glusterd2/commands/snapshot/snapshot-clone.go
glusterd2/commands/snapshot/snapshot-create.go

return HTTP statuscode 400 if request validation fails

---

doc/quick-start-user-guide.md

minor edits around links and re-phrasing.

small set of changes around links

---

glusterd2/config.go
glusterd2/main.go

glusterd2: Allow setting config with environment variables

---

extras/nightly-container/build.sh
extras/nightly-container/provision.yml

Builds containers using buildah and ansible, from nightly RPMs of
GlusterD2 and GlusterFS.

extras/nightly-container: Scripts to build nightly container

---

plugins/bitrot/bitd.go
plugins/bitrot/rest.go
plugins/bitrot/scrubd.go
plugins/bitrot/transactions.go
plugins/bitrot/validate.go

done code clean up where its required in bitrot plugin.
updated code for missing error handling,
if called function is returning an error,
instead of logging with the logger.WithFileds() log with the logger.Error()
updated endpoints.md

Bitrot plugin code clean up

---

glustercli/cmd/bitrot.go
glustercli/cmd/common.go
glustercli/cmd/device.go
glustercli/cmd/events.go
glustercli/cmd/georep.go
glustercli/cmd/glustershd.go
glustercli/cmd/peer.go
glustercli/cmd/root.go
glustercli/cmd/snapshot-activate.go
glustercli/cmd/snapshot-clone.go
glustercli/cmd/snapshot-create.go
glustercli/cmd/snapshot-deactivate.go
glustercli/cmd/snapshot-delete.go
glustercli/cmd/snapshot-info.go
glustercli/cmd/snapshot-list.go
glustercli/cmd/snapshot-restore.go
glustercli/cmd/snapshot-status.go
glustercli/cmd/snapshot.go
glustercli/cmd/volume-create.go
glustercli/cmd/volume-reset.go
glustercli/cmd/volume-set.go
glustercli/cmd/volume.go
glustercli/generate_bash_completion/main.go
glustercli/main.go

cli: Refactor some of glustercli code

---

glusterd2/transaction/transaction.go

if nodes are unreachable and `DontCheckAlive` flag is set, we need to discard
the error message and return nil
Fixes: #1140 

discard error message if node is unreachable and DontCheckAlive flag is set

---

e2e/bitrot_test.go
e2e/georep_test.go
e2e/glustershd_test.go
e2e/peer_ops_test.go
e2e/quota_enable.go
e2e/restapi_auth_test.go
e2e/restart_test.go
e2e/smartvol_ops_test.go
e2e/snapshot_ops_test.go
e2e/utils_test.go
e2e/volume_ops_test.go
e2e/webhook_test.go
glustercli/cmd/common.go
glustercli/cmd/georep.go
pkg/restclient/common.go
pkg/restclient/common_test.go
pkg/restclient/tlsconfig.go

added separate method to create http.Request.
Initializing underlying http.Client while initializing
GlusterD rest client

restclient: refactor some of the rest client code

---

.github/ISSUE_TEMPLATE.md

the content of the template file is taken from heketi.
This template can be used to create an issue
or this can be used for any feature request.

adding a template file to create an issue

---

glustercli/cmd/root.go
glustercli/cmd/utils.go
glustercli/cmd/volume.go

cli: warning prompt yes/no before volume deletion

---

glusterd2/commands/snapshot/snapshot-delete.go

return nil response body for delete operation

---

e2e/volume_ops_test.go
glustercli/cmd/volume-create.go
glusterd2/commands/volumes/volume-option.go
glusterd2/commands/volumes/volume-start.go
glusterd2/commands/volumes/volume-stop.go
glusterd2/volume/store-utils.go
glusterd2/xlator/actors.go
pkg/api/volume_req.go
plugins/glustershd/actor.go
plugins/quota/actor.go

Start/Stop daemons during volume start and stop 

---

glusterd2/commands/volumes/common.go
glusterd2/commands/volumes/optiongroup-create.go
glusterd2/commands/volumes/optiongroup-delete.go
glusterd2/commands/volumes/optiongroup-list.go

check `resp.Count` is greater than the index value which we are accessing from ETCD response

check resp.Count is greater than the index value

---

e2e/smartvol_ops_test.go
e2e/utils_test.go
glusterd2/commands/volumes/volume-delete.go
glusterd2/commands/volumes/volume-smartvol-txn.go
glusterd2/volume/volume-utils.go
plugins/device/deviceutils/utils.go

On Volume delete,
- Unmount the Brick
- Remove LV
- Remove Thinpool
Fixes: #938

Delete bricks on Volume delete if bricks are auto provisioned

---

glusterd2/transaction/step.go

txn: Fix passing nil context in Undo()

---

e2e/utils_test.go

...and add log so that we can see what's being unmounted.
Updates #1209 

Try force unmounting in e2e tests

---

glustercli/cmd/snapshot-info.go

Fixes: https://github.com/gluster/glusterd2/issues/1225
@rafikc30 Please review

Adding snapshot description in glustercli snapshot info

---

glusterd2/commands/volumes/volume-delete.go

Add instrumentation to trace volume delete operation. Add the requestID
and volume name as an attribute in the top level span of the trace.
Closes #1202

Tracing: Trace volume delete operation

---

e2e/volume_ops_test.go
glusterd2/volume/volume-utils.go
pkg/api/volume_resp.go

disperse data count and redundancy count added to API response

---

glusterd2/servers/sunrpc/server.go

Used the lock file to find any other glusterd2 running with same
socket file in use.
Fixes: #1246

cleanup `glusterd2.socket` during start

---

pkg/restclient/common.go

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

Add Version() to REST client

---

glusterd2/commands/volumes/volume-create-txn.go
glusterd2/volume/struct.go

Required for replace Brick and LVM expand.
@vpandey-RH @aravindavk

Storing SnapshotReserveFactor in VolInfo struct

---

glusterd2/brick/types.go
glusterd2/commands/snapshot/snapshot-create.go
glusterd2/volume/struct.go

we are setting the value of subvol type from an uninitialized
variable.
Fixes #1278

snapshot/create: Fix subvol type setting to first value

---

glusterd2/commands/snapshot/snapshot-deactivate.go
pkg/errors/error.go

Move snapshot error msg to error pkg

---

e2e/volume_ops_test.go
glusterd2/bricksplanner/subvoltype_disperse.go
glusterd2/bricksplanner/subvoltype_distribute.go
glusterd2/commands/volumes/volume-create-txn.go
glusterd2/volume/struct.go

check brick type for volume creation

---

glustercli/cmd/snapshot-create.go

Fix typo in snapshot create CLI flag

---

glustercli/cmd/root.go

Endpoints are taken in following order of precedence
(highest to lowest):
- --endpoints
- GD2_ENDPOINTS (environment variable)
- (default value)
Fixes: #1291

Environment variable support for glustercli endpoints

---

extras/nightly-rpms.sh

Also address shellcheck failure in test/020-test-shellscripts.sh

Fix nightly-rpms script

---

glusterd2/volgen/volfile_brick.go

Fix issue with experimental xlator

---

glusterd2/volgen/volfile_brick.go

Remove sdfs xlator

---

glusterd2/store/store.go

If etcd goes down and comes up then existing session lease
will not be refreshed and expires after lease ttl duration.
This closes #1054

etcd: session lease expires if there is reconnection to etcd server

---

e2e/glustershd_test.go
plugins/glustershd/api/resp.go
plugins/glustershd/rest.go

Fixes [#1306](https://github.com/gluster/glusterd2/issues/1306)

Heal-info command fails when any one of the bricks is offline

---

plugins/device/api/resp.go

device/plugin: rename used to device-used in api response

---

e2e/smartvol_ops_test.go
e2e/snapshot_ops_test.go
glustercli/cmd/utils.go
glustercli/cmd/volume-create.go
glusterd2/bricksplanner/planner.go
glusterd2/bricksplanner/subvoltype_replicate.go
glusterd2/commands/volumes/volume-create.go
glusterd2/options/options.go
plugins/device/deviceutils/utils.go

Fixes: https://github.com/gluster/glusterd2/issues/1135

Using bytes instead of KB for volume creation

---

e2e/lvmtest/lvmtest.go
e2e/smartvol_ops_test.go
e2e/snapshot_ops_test.go
glusterd2/snapshot/lvm/lvm.go

Change generic loopback device name to gluster specific

e2e/snapshot:Fix spurious failure in snapshot test

---

e2e/smartvol_ops_test.go
glustercli/cmd/volume.go
glusterd2/commands/volumes/volume-expand-txn.go
glusterd2/commands/volumes/volume-expand.go
pkg/api/volume_req.go
pkg/errors/error.go
plugins/device/deviceutils/store-utils.go

Fixes [#852](https://github.com/gluster/glusterd2/issues/852)
Intelligent Volume expand by lvm extension

Intelligent Volume Expand API & CLI

---

e2e/volume_ops_test.go
glustercli/cmd/volume.go
glusterd2/commands/volumes/volume-expand-txn.go

Arbiter count was not considered when a Volume is expanded.
Fixes: #1161

Fix expanding arbiter volume

---

doc/geo-replication.md

Not yet added to the index file. I will add it once PR #1035 gets
merged.

doc: Geo-replication feature documentation

---

e2e/georep_test.go
extras/centos-ci.sh
extras/nightly-container/provision.yml

added pending geo-replication  e2e test cases.

geo-rep e2e test cases

---

glusterd2/volgen/defaults.go
glusterd2/volgen/volgen.go

Fix xlator names in generated volfiles

---

pkg/logging/logging.go

create a custom log.Formatter which switches to UTC
Fixes: #1355

logging: log in UTC timezone

---

glusterd2/xlator/load.go

If `.options` is null in xlator_api then glusterd2
was failing. This PR adds nil check to prevent this failure.

Fix xlator .so read failure if no options

---

e2e/smartvol_ops_test.go
glustercli/cmd/glustershd.go
glusterd2/brickmux/demultiplex.go
glusterd2/brickmux/reconcile.go
glusterd2/commands/snapshot/snapshot-clone.go
glusterd2/commands/snapshot/snapshot-delete.go
glusterd2/commands/volumes/volume-delete.go
glusterd2/commands/volumes/volume-profile.go
glusterd2/commands/volumes/volume-smartvol-txn.go
glusterd2/transactionv2/engine.go
glusterd2/transactionv2/steprunner.go
glusterd2/volgen/common.go

Fixed:
* ineffectual assignments in Go code.
* misspelled English words
* linter for Go source code.

Fix issues found in go report

---

e2e/brickmux_test.go
glustercli/cmd/volume.go

* Fix spelling mistake.
* Print volume capacity, used and free size in the human-readable format.

print volume capacity, Used and free size in human readable format

---

glustercli/cmd/device.go

Add device info cli command
* Added device info CLI command, which
will list the devices if the Peer ID is
passed or else it will list all devices
in the cluster.
```
[root@dhcp43-209 build]# ./glustercli device info
Peer Name: dhcp43-209.lab.eng.blr.redhat.com
Peer ID: 335f3b47-cdc6-46ad-806e-6340f867c428
+----------+---------+------------+-----------+-----------+--------+
|  DEVICE  |  STATE  | TOTAL SIZE | FREE SIZE | USED SIZE | USED % |
+----------+---------+------------+-----------+-----------+--------+
| /dev/vdb | enabled | 0.0 B      | 0.0 B     | 0.0 B     |   0.00 |
| /dev/vdc | enabled | 199.9 GiB  | 129.1 GiB | 70.8 GiB  |  35.41 |
+----------+---------+------------+-----------+-----------+--------+
Peer Name: dhcp43-106.lab.eng.blr.redhat.com
Peer ID: …
```

Add device info CLI command

---

glusterd2/transaction/lock.go

Instead of using a global etcd session create a new etcd session
everytime a lock is created.
If we use existing session every time when a lock is created then
etcd lock will use same leaseId. It leads to faulty lock behaviour.

cluster-lock: fix getting cluster wide etcd lock

---

Gopkg.lock
Gopkg.toml

adding prune will discard pulling of
unwanted files, non go codes, and test
files.

add prune to Gopkg.toml file

---

e2e/peer_ops_test.go
glusterd2/commands/peers/addpeer.go

Add online status to peer add response

---

e2e/brickmux_test.go
glusterd2/commands/volumes/volume-expand-txn.go

Fixes [#1303](https://github.com/gluster/glusterd2/issues/1303)
Issue -
Add bmux support for volume-expand feature
Fix -
During starting the newly added bricks, check if bmux is enabled. If it is enabled
then traverse over all the local bricks present in the newly added bricks list and
look for a target brick from any of the started volumes(which have a brick on the node on which the current brick exists) present in the cluster.
If a target brick is not found due to any reason then start a new seperate glusterfsd for that particular brick.

Bmux support for volume expand

---

glusterd2/commands/volumes/volume-delete.go
glusterd2/commands/volumes/volume-start.go
glusterd2/commands/volumes/volume-stop.go

Migrate volume operations(start,stop,del) to new txn framework

---

e2e/peer_ops_test.go
glusterd2/commands/peers/addpeer.go
pkg/errors/error.go
pkg/utils/peerutils.go

check connectivity to peer before sending join cluster request.

---

glusterd2/commands/volumes/volume-delete.go
glusterd2/commands/volumes/volume-option.go
glusterd2/commands/volumes/volume-start.go
glusterd2/commands/volumes/volume-stop.go
glusterd2/volume/store-utils.go
plugins/device/transaction.go

If the details already available as API response, additional logging
for success is removed.

Removed redundant log messages

---

glusterd2/transactionv2/cleanuphandler/cleanup_handler.go
glusterd2/transactionv2/engine.go
glusterd2/transactionv2/steprunner.go
glusterd2/transactionv2/transaction.go
glusterd2/transactionv2/txnmanager.go

- increase timeout for txn to get complete to 3 Minutes
and sync timeout to 2 Minutes.

transaction: increase timeout for transaction

---

plugins/blockvolume/blockprovider/gluster-virtblock/gluster_virtblock.go
plugins/blockvolume/init.go

plugins/gluster-virtblk: Rename block to gluster-virtual block

plugins/gluster-virtblock: Rename to virtual block

---

pkg/restclient/block_volume.go

Fix gluster virtual block restclient api 

---

glusterd2/commands/volumes/volume-options-get.go

Fixes:https://github.com/gluster/glusterd2/issues/1445
Signed-off-by: rishubhjain <rishubhjain47@gmail.com>

Fixing volume set options functionality

---

glusterd2/volgen/common.go

Fix thin arbiter Option name

---

glusterd2.toml.example
glusterd2/options/cluster.go
plugins/blockvolume/hostvol_manager.go
plugins/blockvolume/hostvol_opts.go

blockVolume: use cluster-options for host volume configuration

---

glusterd2/transactionv2/cleanuphandler/cleanup_handler.go
glusterd2/transactionv2/transaction.go

expose all txn related timeouts as expvars

---

glusterd2/transactionv2/engine.go
glusterd2/transactionv2/transaction.go
glusterd2/transactionv2/txnmanager.go

initiator will add trasactions under pending-transaction/transaction/
key. Txn Engine keeps a watch on this key for new transactions
and execute transactions.
eg.. etcd key for storing details of a single transaction:-
`pending-transaction/transaction/<txn-ID>`

transaction: adding txns under pending-transaction/transaction/ key

---

glusterd2/transactionv2/cleanuphandler/cleanup_handler.go

broadcast an event on election of cleanup leader

---

glusterd2/store/liveness.go
glusterd2/transactionv2/transaction.go

Check aliveness of all nodes in a single etcd query

---

glusterd2/transaction/lock.go
pkg/backoff/backoff.go
pkg/backoff/backoff_test.go

added method for acquiring txn Lock with retry mechanism
