gluster/glusterd2

tests/assert.go, volume/volume_test.go
Removed the dependency on github.com/ heketi/heketi just for the
Assert() function. 'Borrowed' the implementation from
github.com/heketi/heketi pkg with attribution placed in tests/assert.go
Signed-off-by: Krishnan Parthasarathi <kparthas@redhat.com>
=> closes #19, removed dependency on heketi

.gitreview, README.md
As we no longer use gerrithub, all references to it have been removed
from the repository.
Also, a badge to waffle.io has been added to the README.
Closes #18
=> Remove gerrithub references

utils/utils.go, volume/struct.go, volume/utils_misc.go
This also makes the type of ID field of volume object from string to uuid.
Closes #32
=> Use uuid.NewRandom() to maintain uniformity in uuid generation

volume/store-utils.go, volume/struct.go
1. This patch fixes ValidateBrickEntries() to use correct bricks
2. AddOrUpdateVolume() in store was not using volume prefix to store the volumes
due to which getVolume(s) was always failing
Closes #47
=> fix volume create issues

COPYING, README.md
Following the GlusterFS project, GD2 is also licensed under GPLv2.
Closes #59
=> Add license

scripts/check-reqs.sh, scripts/install-reqs.sh
Install etcd while executing install-reqs.sh (all necessary package for
GlusterD 2.0).
Issue #70
Signed-off-by: Gaurav Kumar Garg <garg.gaurav52@gmail.com>
=> Install etcd as a package requirement for GlusterD 2.0

etcdmgmt/etcd-mgmt.go, etcdmgmt/etcd-mgmt_test.go
Kill() call should followed by Wait() before restarting any process
Closes #80
=> Fix test in TestIsETCDStartNeeded

context/myuuid.go
The value of os.ModePerm which is passed as argument to method
ioutil.WriteFile() is 0777 by default.
=> Remove execute bit for file that stores UUID

config/config.go, etcdmgmt/etcd-mgmt.go, main.go, rest/rest.go, rpc/client/peer-rpc-clnt.go, rpc/server/listener.go, volgen/core.go
* Remove hard-coded RPC port 9876
* Log pid of glusterd2 process on start
* Log ports that glusterd2 listens on
Remove a TODO about using unix.Setpgid because:
A process can set PGID of only itself and its children. And it can't
change the PGID of its children after that child has called one of the
functions of exec family. execve() is invoked internally in Cmd.Start()
=> Minor fixups

config/config.go, rest/rest.go, rpc/client/peer-rpc-clnt.go, rpc/server/listener.go
Currently, both the RPC and REST services bind to their respective
ports on all network interfaces. This may not always be desirable.
For example, when a machine is part of multiple networks, the
admin may want to make the REST service available only on one
network interface for external consumption.
This change adds command line options to specify both IP and port
these services should bind to. The default behaviour is not changed
i.e bind on all available interfaces.
=> Allow binding to specific network interface

Makefile
The default of 12 is too much and can hang your system.
=> makefile: Reduce gometalinter parallel jobs to 4

config.go, etcdmgmt/etcd-mgmt.go, main.go
Remove the hardcoded paths for etcd and make RunDir and LogDir
configurable.
=> config,etcdmgmt: Remove hardcoded paths

utils/utils.go
During review of daemon-framework PR, these functions were copied from
utils package to daemon package which consumes them. However, I missed
removing these from utils package. Doing that now.
=> Residual cleanup of utils

daemon/daemon.go
glusterfsd, when spawned will exit because:
* Directories in logfile path and pidfile path don't exist
* It tries to use portmap and communicate with glusterd to get volfile.
This isn't implemented yet.
When glusterfsd dies immediately after spawn, it'll become zombie if
exit status of the process isn't read by parent.
This change also moves the code that reads pid file to place where it
really should be. Also checks if process is really running before it
returns success to the caller.
=> Don't let child process become zombie

.gitignore, Makefile, scripts/build.sh, scripts/release.sh
- The Makefile has been updated to use these scripts to build, install
and release
- Run `make release` to create build, create and sign a release archive,
useful for releasing on Github.
=> Add scripts to build and release GD2

extras/test-env/Dockerfile, extras/test-env/README.md, extras/test-env/Vagrantfile, extras/test-env/build.sh, extras/test-env/hooks/build, extras/test-env/setup.sh
This required to setup auto-triggering builds of images whenever a new
tag/release is done. Without this the build script has to be manually updated
and builds manually triggered on Docker hub.
=> Changes for auto building test-env docker images

brick/brick.go, brick/port.go, config.go, daemon/daemon.go, etcdmgmt/etcd-mgmt.go, gdctx/global.go, main.go, peer/self.go, peer/store-utils.go, transaction/rpc-client.go, transaction/step.go, utils/utils.go, utils/utils_test.go, utils/volumeutils.go, volgen/core.go, volume/store-utils.go, volume/struct.go
Barring transaction subpackage which contains mainly generated code,
other subpackages have had their golint warnings fixed.
We would want to ensure that all new code adheres to golint.
Signed-off-by: Prashanth Pai ppai@redhat.com
=> Fix golint warnings

main.go
As part of earlier golint fixes, this wasn't fixed correctly
and the code logic was inadvertently changed.
=> Fix Restart bool check

commands/peers/addpeer.go, commands/peers/deletepeer.go, commands/peers/peer-rpc-svc.go, etcdmgmt/client.go, glide.lock, peer/peer.go, peer/self.go
- Implements etcd client v3
- Implements wrapper functions for etcd member operations i.e
(add, remove, list) etcd members
- The etcd member id was of type string in v2.
In v3, the member id is of type uint64.
- The client connections are  now cleanly shutdown before
etcd server is restarted.
This PR closes issue #162
=> Migrate to etcd client v3

etcdmgmt/client.go
Adding a etcd member that is already part of the cluster is an error
case, as it should be.
The response object is nil during an error response from client v3 API.
However, this behaviour isn't clearly defined in client v3 API doc.
Closes #167 
=> Fix crash when adding peer that exists

commands/peers/deletepeer.go
Problem
*******
Bring up two glusterd2 nodes - A and B. Add B as peer from node A.
Now removing peer A from node B does not work. Why ? Because in
delete peer, we first remove the member from cluster and then
remove the entry from the store. This isn't right as there is a
loss of quorum (no leader) for a brief period of time. Hence, removing
peer entry from store fails.
Fix
***
Change the order. First remove peer entry from store and then remove
the node from etcd cluster.
Closes #171
=> Fix deleting peer from remote node

commands/peers/peer-rpc-svc.go, etcdmgmt/client.go, main.go
glusterd2 uses internal etcd client only during member add, list, delete.
All access for storing information in etcd cluster is done through libkv.
So there is no good reason for the internal etcd client to always remain
connected to etcd server throughout the lifecycle of the process.
This also removes the need to restart/reconfigure etcd client whenever
the glusterd2 instance joins/leaves an etcd cluster.
=> Make etcd client connections non-persistent

brick/brick.go, commands/volumes/commands.go, commands/volumes/volume-status.go, transaction/context.go, transaction/context_mock.go, volume/struct.go
**Implement volume status endpoint:**
Querying for the status of volume will result in network calls to only
those nodes that contain bricks that make up the volume.
The transaction initiator node aggregates the results from various
nodes and sends it back to client.
This also serves as an example that the transaction framework need
not do the result aggregation part. The nodes can use transaction
context to store results. The initiator node then can do it's own
implementation (this is largely op-specific) to collate results stored
in transaction context and send the aggregated result to client.
=> Implement volume status as example of transaction result aggregation

commands/volumes/volume-create.go, commands/volumes/volume-create_test.go, utils/utils.go
Problem:
The volume ID was being generated multiple times, once each on the node
or instance which make up the volume. This is because the method
'validateVolumeCreate' was run on all nodes that are part of transaction
and this method was generating a new volume ID. As a result the volume
ID in xattr set on each brick would be different.
Fix:
Only the initiator node should generate the volume id once, set it in the
transaction context, so that every other node/instance can make use of
that.
Closes #191 
=> Fix volume ID mismatch

brick/brick.go
... instead of hardcoding the path
=> Use `exec.LookPath` to find `glusterfsd` in $PATH

brick/brick.go, commands/volumes/volume-start.go, commands/volumes/volume-stop.go, daemon/daemon.go
This fixes the TOCTOU race for brick port by:
* Starting bricks sequentially (per instance).
* Detect when glusterfsd process exits with EADDRINUSE
Closes #193 
=> Avoid race in brick port allocation and use

config.go, glusterd.json.example, glusterd.toml.example, glusterd.yaml.example, peer/self.go, rest/rest.go, rpc/server/listener.go, utils/peerutils.go
The name of the configurable options should represent the services
provided or consumer of the port and not the protocol used.
* Renamed 'rpcaddress' to 'peeraddress': Denotes the address used
for peer to peer communication.
* Renamed 'restaddress' to 'clientaddress': Denotes the address
used by clients to communicate with glusterd2.
Coincidentally, these are analogous to those provided by etcd.
=> Name configurable addresses to be more meaningful

glide.lock, glide.yaml, main.go, rest/rest.go
Use cmux, which is a connection multiplexer. cmux matches the
connection when it's accepted. This still doesn't support multiple
protocols over same connection, but that is not what we want.
Closes issue #220
=> Multiplex different protocols over the same port

glide.lock, glide.yaml, main.go, rpc/sunrpcserver/dict.go, rpc/sunrpcserver/handshake_prog.go, rpc/sunrpcserver/server.go, scripts/lint-check.sh
The client port will now be used for serving both HTTP client requests
and also Sun RPC requests. This initial patch implements the getspec
function. Other functions can be added later.
Closes issue #224 
=> Introduce Sun RPC server

glide.lock, rpc/sunrpcserver/common.go, rpc/sunrpcserver/dump_prog.go, rpc/sunrpcserver/handshake_prog.go, rpc/sunrpcserver/portmap_prog.go, rpc/sunrpcserver/program.go, rpc/sunrpcserver/server.go, scripts/lint-check.sh
This PR refactors and simplifies the process of adding new RPC programs
and new procedures. Following RPC programs have been introduced
(procedures are not exhaustive yet) on top of it:
`Glusterfs Handshake`
`Gluster Dump`
`GlusterFS Portmap`
=> Add mount rpc programs

rpc/sunrpcserver/server.go
ServeRequest synchronously serves a single request. ServeCodec runs
the server on a single connection. ServeConn blocks, serving the
connection until the client hangs up.
=> Use ServeCodec in sunrpc server

commands/peers/peer-rpc-svc.go, etcdmgmt/server.go, main.go
The etcd data dir, WAL dir and config file should only be wiped during
peer add and peer delete operations.
Closes #232 
=> Do not wipe etcd local data on glusterd2 exit

brick/brick.go, commands/volumes/volume-start.go
This originated from the recent brick multiplex merge.
Here's the symptomatic fix in gluster for the crash.
diff --git a/xlators/protocol/server/src/server.c b/xlators/protocol/server/src/server.c
index 5be900a..ed34aba 100644
--- a/xlators/protocol/server/src/server.c
+++ b/xlators/protocol/server/src/server.c
@@ -1236,8 +1236,10 @@ init (xlator_t *this)
}
#endif
-        FIRST_CHILD(this)->volfile_id
-                = gf_strdup (this->ctx->cmd_args.volfile_id);
+        if (this->ctx->cmd_args.volfile_id) {
+                FIRST_CHILD(this)->volfile_id
+                        = gf_strdup (this->ctx->cmd_args.volfile_id);
+        }
this->private = conf;
ret = 0;
=> Fix glusterfsd crash on glusterfs master

glide.lock, servers/sunrpc/server.go
sunrpc codec can now notify (via a channel) whenever a sunrpc client
connection is closed. The sunrpc server maintains a list of clients
which is updated on connection and disconnection.
But there is no provision yet to know if these sunrpc clients are
glusterfs mount processes or something else.
=> Get notified on sunrpc clients' disconnection

utils/peerutils.go
Peers hostnames without explicitly specified
port will be extended with default port values.
Fixes #280
Signed-off-by: Denis Chaplygin <dchaplyg@redhat.com>
=> Fixed parsing portless peer hostname.

config.go, logging.go, main.go
New CLI flag "logfile" added. Default value is "-" which writes to
StdErr. Logfile can be specified using,
./glusterd2 --logfile glusterd.log
NOTE: Use the flag `--logdir` to configure the log directory if required
./glusterd2 --logfile glusterd.log --logdir /var/log/glusterfs
Also added support for logrotate, if log file rotated, notify the running
glusterd process by sending SIGHUP(`kill -SIGHUP $PID`)
Closes #274
=> Added Logfile support

commands/volumes/volume-create.go, commands/volumes/volume-delete.go, commands/volumes/volume-info.go, commands/volumes/volume-list.go, commands/volumes/volume-start.go, commands/volumes/volume-status.go, commands/volumes/volume-stop.go, glide.lock, glide.yaml, middleware/request_id.go, middleware/request_logging.go, servers/rest/rest.go, servers/rest/utils/utils.go, transaction/simple.go, transaction/transaction.go
* Introduces two minimal middlewares:
1. Request logger: logs all incoming REST requests
2. Request ID Generator: Assigns a request ID to each request
* Middlewares are easily chained using alice.
https://justinas.org/alice-painless-middleware-chaining-for-go/
* Removes a lot of old logging junk. Uses request scoped logger.
TODO: Use context and opentracing in future
Closes #287
=> Introduce middlewares and do some cleanup

glide.lock, servers/sunrpc/callback.go, utils/utils.go
This callback mechanism is used to send notifications to RPC clients.
Closes #259
=> Implement RPC callbacks

commands/volumes/volume-create.go, commands/volumes/volume-delete.go, commands/volumes/volume-stop.go, transaction/lock.go
Transactions shouldn't wait forever to obtain a lock. If there is another
conflicting transaction in progress and current txn does not get a lock
for a certain period of time (set to 5 seconds), a 409 (HTTP Conflict)
response is sent to the client.
=> transaction: Use timeouts for etcd mutexes

commands/peers/peer-rpc-svc.go, e2e/config/3.yaml, e2e/peer_ops_test.go, e2e/volume_ops_test.go, pkg/elasticetcd/volunteer.go, store/config.go, store/store.go
Instead of using the provided store config values, store was being
restarted with the default store config. This prevented GD2 from working
when non-default config is used.
A test has been added to the e2e suite to check this.
=> Use proper store config when restarting store during probe

utils/utils.go
The index xlator expects glusterd to create that directory.
This is needed until https://review.gluster.org/#/c/18003/ is merged.
Closes #353 
=> Create .glusterfs/indices as a workaround

commands/peers/addpeer.go, commands/peers/deletepeer.go, commands/peers/errors.go, commands/peers/peer-rpc-svc.go, commands/volumes/common.go, commands/volumes/volume-create.go, commands/volumes/volume-create_test.go, commands/volumes/volume-expand.go, commands/volumes/volume-option.go, pkg/elasticetcd/leader.go, servers/sunrpc/handshake_prog.go, volgen/core.go
This will ensure that all nodes will have access to client volfile to serve
glusterfs clients (mounts). The client volfile will only be (re)generated
on the transaction's initiator node.
Closes #185, #340
=> Store client volfile in etcd

cli/cmd/common.go, cli/cmd/root.go
./build/glustercli --host=http://node1:24007 peer status
Updates: #205
=> cli: Added host flag to use CLI from different node

commands/volumes/common.go, commands/volumes/volume-create.go, commands/volumes/volume-option.go, e2e/volume_ops_test.go, pkg/api/req.go, volume/volume-utils.go, xlator/global.go, xlator/xlator.go
Volume options can now be of the form `<graph>.<xlator>.<option>` where `<graph>`
is optional and when omitted, the option change shall be applied (by volgen)
to instances of the xlator loaded in all graphs.
=> Allow option of the form <graph>.<xlator>.<option>

xlator/options.go, xlator/options.h, xlator/xlator.go
Loading xlator options in glusterd2 was broken when new fields were added to
volume_option_t struct by this patch: https://review.gluster.org/18059
P.S: This also means that glusterd2 is now only compatible with the latest
glusterfs master.
Closes issue #366 
=> Parse newly added fields of volume_option_t struct

brick/glusterfsd.go, brick/types.go, cli/cmd/volume.go, commands/volumes/brickutils.go, commands/volumes/volume-create_test.go, commands/volumes/volume-expand.go, commands/volumes/volume-start.go, commands/volumes/volume-stop.go, e2e/restart_test.go, e2e/volume_ops_test.go, peer/store-utils-mock.go, pkg/api/resp.go, servers/sunrpc/handshake_prog.go, utils/utils.go, utils/utils_test.go, volgen/client-template.go, volgen/core.go, volume/struct.go, volume/volume-utils.go, volume/volume_test.go
* Remove Hostname field from Brickinfo
* Remove "remote-host" hardcoded in client volfile
* Fix unit tests, logging and e2e tests accordingly
* Add String() method to Brickinfo type
This partially fixes issues #356 
TODO (separate PR): Add REST API to change IP address of the peer.
=> Make UUID:path as the ONLY way of specifying brick during volume create

brick/glusterfsd.go, glide.lock, glide.yaml
MD5 will be phased out of Gluster, and xxhash is the most popular
replacement for non-security related uses. So GD2 should as well.
See: gluster/glusterfs#230
=> Replace md5 with xxhash

e2e/main_test.go, e2e/volume_ops_test.go, extras/centos-ci.sh
TestVolumeOptions used to be skipped on CentOS CI as it didn't have glusterfs
installed from source. Fixed that test to reflect change in volume create API.
`TestVolumeOptions` is not skipped anymore. GlusterFS is installed from source, for now.
`make test` when run as non-root only runs unit tests now.
=> Fix TestVolumeOptions and running unit test as non-root

e2e/georep_test.go, pkg/restclient/georep.go, plugins/georeplication/api/req.go, plugins/georeplication/api/resp.go, plugins/georeplication/errors.go, plugins/georeplication/init.go, plugins/georeplication/rest.go, plugins/georeplication/store-utils.go, plugins/georeplication/transactions.go, plugins/plugins.go
REST API to create Geo-replication session create
POST /v1/geo-replication/:mastervolid/:slavevolid
Request body,
{
"mastervol": MASTER_VOL_NAME,
"slavevol": SLAVE_VOL_NAME,
"slavehosts": LIST_OF_SLAVE_HOSTS,
"slaveuser": SLAVE_USER
}
Updates: #271
=> plugins/geo-rep: Geo-replication Session Create

pkg/restclient/georep.go, plugins/georeplication/gsyncd.go, plugins/georeplication/init.go, plugins/georeplication/rest.go, plugins/georeplication/transactions.go
REST API:
POST /v1/geo-replication/:mastervolid/:slavevolid/start
This API depends on the Geo-rep refactoring
patch(https://review.gluster.org/18257), not added any
tests since start of gsyncd will fail.
I need to find best way to not hard code the path of gsyncd
binary. That can be addressed in different patch.
Updates: #271
=> plugins/georep: Geo-replication session start

commands/volumes/volume-stop.go, daemon/daemon.go, daemon/store.go
This should prevent glusterd2 from spawning bricks of volume that is
in stopped state, during glusterd2's restart.
Fixes #408
=> Remove brick entry from store on volume stop

glustercli/cmd/volume.go, pkg/api/volstate.go, pkg/api/voltype.go
Except Bricks list(Currently shows as NODEID:BRICKPATH), all
other fields output matches with existing Gluster CLI output
=> cli: Match gluster volume info output to Glusterd1

glusterd2/volgen/template.go
If Template directory is not empty then new default templates added to
$SRC/glusterd2/volgen/static.go was not generated. This patch checks
each default template file existence and regenerates it if not exists.
Fixes: #458
=> volgen: Generate default templates even if template dir not empty

glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-delete.go, glusterd2/commands/volumes/volume-expand.go, glusterd2/commands/volumes/volume-info.go, glusterd2/commands/volumes/volume-option.go, glusterd2/commands/volumes/volume-start.go, glusterd2/commands/volumes/volume-status.go, glusterd2/commands/volumes/volume-stop.go, glusterd2/transaction/context.go, glusterd2/transaction/transaction.go, plugins/georeplication/rest.go
Do not fail the transaction if few of the nodes are down.
Changes to transaction framework:
* Check if nodes are up is now configurable
* Transaction framework users need not explicitly set the list of nodes to be checked for liveness
* Add option to not rollback and ignore failures.
Closes #475
=> Volume Status: Handle nodes being down

glusterd2/store/embed.go, glusterd2/store/liveness.go, glusterd2/store/remote.go, glusterd2/store/store.go
All etcd interfaces that needed to be namespaced (KV, Lease, Watcher,
Session) have been namespaced properly, for both remote store and
embedded stores.
As the etcd interfaces were not namespaced, some store operations
happened out of namespace. Also, elasticetcd unintentionally got
namespaced, causing some of its operations to happen in GD2s namespace.
=> store: Correctly namespace etcd client

glusterd2/commands/peers/peer-rpc-svc.go, glusterd2/commands/volumes/events.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-delete.go, glusterd2/commands/volumes/volume-start.go, glusterd2/commands/volumes/volume-stop.go, glusterd2/daemon/daemon.go, glusterd2/daemon/events.go, glusterd2/events/eventhandler.go, glusterd2/events/events.go, glusterd2/events/global.go, glusterd2/events/logger.go, glusterd2/main.go
The events framework allows events to be generated and broadcast internally
within the GD2 cluster, with `events.Broadcast(Event)`.
`Event`s are either local or global. Local events are broadcast just locally
within a GD2. Global events are broadcast globally to other GD2s.
Interested parties can register handlers for all or specific events using
`events.Register(EventHandler, events ...string)`
=> Internal events framework

glustercli/cmd/volume.go, glusterd2/commands/volumes/utils.go, glusterd2/commands/volumes/volume-create.go, glusterd2/volume/struct.go, pkg/api/volume_req.go, pkg/api/volume_resp.go
This patch adds partial support for arbiter volume creation and
displaying volume info in the output. brick volgen support is still
pending, wherein we need to insert the arbiter xlator into every 3rd
brick of the replica. For now, even if you create arbiter volume, the
3rd brick becomes a full fledged data brick.
Signed-off-by: Ravishankar N <ravishankar@redhat.com>
=> add arbiter support

constants/constants.go, glusterd2/store/config.go, glusterd2/store/embed.go, glusterd2/store/remote.go, pkg/elasticetcd/client.go, pkg/elasticetcd/config.go, pkg/elasticetcd/server.go
Signed-off-by: Shubhendu <shtripat@redhat.com>
=> Enable TLS authentication for etcd

glusterd2/events/events.go, glusterd2/events/nfs-ganesha.go
If volume is already exported via Ganesha, then during stop the volume
need to be unexport and again re-export during volume start. The old glusterd
does this with help of dbus signals called via wrapper script "dbus-send.sh"
(available in glusterfs 3.10)
TODO :
* need to add validations before calling the script like
i.) ganesha is running or not
ii.) volume is exported or not
* Send a patch to include dbus-send.sh in master branch
Required to fix following issue/bug to work ganesha with GD2
* https://bugzilla.redhat.com/show_bug.cgi?id=1532238
* https://github.com/gluster/glusterd2/issues/518
Thanks ppai for all the help
Fixes: #434
Signed-off-by: Jiffin Tony Thottan <jthottan@redhat.com>
=> NFS-Ganesha integration : Sending dbus signals for start and stop

glusterd2/xlator/options/options.go
The name of the function ValidatePriorityorSize() is misleading.
I tried replicating the same logic as in the validation of priority in options.c in GD1.
=> Add validations for the pairs of elements.

glusterd2/volgen2/volfile_bitd.go, glusterd2/volgen2/volgen.go
Some components like bit-rot uses same xlator for both `bitd` and
`scrubd`, if option `scrubber=on` present in volfile then the daemon
becomes `scrubber` else it becomes `bitd`. While generating `bitd`
volfile `scrubber` option should not be added.
Updates: #431
=> volgen2: Provide option to ignore options

glusterd2/servers/sunrpc/dict/dict.go, glusterd2/servers/sunrpc/handshake_prog.go, glusterd2/volgen2/volfile_scrub.go, glusterd2/volume/volume-utils.go, pkg/errors/error.go, plugins/bitrot/init.go, plugins/bitrot/rest.go, plugins/bitrot/transactions.go
Bitrot scrubber daemon supports ondemand scrub by
providing brick-op service. Glusterd invokes rpc
to avail the service.
Updates: #431
=> bitrot: Add scrub ondemand support

glustercli/cmd/peer.go, glustercli/cmd/volume.go, glusterd2/commands/peers/addpeer.go, glusterd2/commands/peers/deletepeer.go, glusterd2/commands/peers/getpeer.go, glusterd2/commands/peers/getpeers.go, glusterd2/peer/peer.go, glusterd2/peer/self.go, glusterd2/peer/store-utils-mock.go, glusterd2/peer/store-utils.go, glusterd2/transaction/rpc-client.go, glusterd2/volume/struct.go, pkg/api/peer_req_resp.go, pkg/restclient/peer.go
Peer address is used by glusterd2 to communicate with each other. Client address is used by clients (CLI, mount, curl) to communicate with glusterd2. A single `Addresses` currently showed in response and CLI is unusable by clients as it's address used for internal communication
=> Separate Peer and Client Addresses in Peer object

glusterd2/xlator/load.go
Before
> Failed to load xlator options error=stat : no such file or directory
After:
> Failed to load xlator options error=No xlators dir foun
=> xlator: report proper error message when xlator dir is empty

Makefile, scripts/build.sh
This is required for building unbundled RPMs as an unprivileged user.
If not, the golang build process tries to install the built deps into the
system.
=> Selective fast builds

.gitattributes, README.md, doc/endpoints.md, glusterd2/commands/peers/commands.go, glusterd2/commands/volumes/commands.go, glusterd2/servers/rest/rest.go, glusterd2/servers/rest/routes.go, pkg/tools/generate-doc.go
* REST API doc now resides in `doc/` dir and is mentioned in `README.md`
* Added request and response structs to peer APIs
* The `/statedump` and `/endpoints` now follow the normal convention of registering a mux route.
* Added some useful comments about further pending TODOs
* Add generated doc to `.gitattributes` to suppress GitHub showing diff.
=> Fix few pending stuff in REST API doc generation

glusterd2/brick/types.go, glusterd2/volgen2/clustergraph.go, glusterd2/volgen2/volfile_bitd.go, glusterd2/volgen2/volfile_fuse.go, glusterd2/volgen2/volfile_gfproxy.go, glusterd2/volgen2/volfile_quotad.go, glusterd2/volgen2/volfile_rebalance.go, glusterd2/volgen2/volfile_scrub.go, glusterd2/volgen2/volfile_shd.go
If Remove brick is started, rebalance volfile expects details
about the list of decommissioned bricks.
Example:
option decommissioned-bricks testvol2-client-0
When remove brick starts, Set `brickinfo.Decommissioned=true`
Updates: #426
=> volgen: decommissioned bricks details in Volfile

glusterd2/commands/volumes/volume-expand.go
Add brick behavior is,
- If replica count is changed, add brick appends brick to existing subvols
- If replica count is same, Creates new subvol
In case of single subvol, Replica count is not changed so new bricks are
getting added as new subvolume. This patch fixes the issue and adds the
bricks if Subvolume Type is "Distribute"
Fixes: #578
=> Add brick issue fix for Volume with single sub volume

glusterd2/xlator/options/options.go, glusterd2/xlator/validation.go
Various quota options we set as quota set command in glusterd one.
From glusterd2 onwards they are maintained through volume set commands.
this patch enables setting quota options like soft and hard timeout,
deemstatfs, alert-time and default-soft-limit.
The parsing for time during volume set was bug, have changed it to
accomodate the backward compatiblity with glusterd1's validation.
Updates: #421
=> Quota: to set quota options

glusterd2/commands/global/getglobaloptions.go, glusterd2/commands/global/setglobaloptions.go, glusterd2/commands/peers/addpeer.go, glusterd2/commands/peers/deletepeer.go, glusterd2/commands/peers/getpeer.go, glusterd2/commands/peers/getpeers.go, glusterd2/commands/volumes/bricks-status.go, glusterd2/commands/volumes/optiongroup-create.go, glusterd2/commands/volumes/optiongroup-delete.go, glusterd2/commands/volumes/optiongroup-list.go, glusterd2/commands/volumes/volfiles.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-delete.go, glusterd2/commands/volumes/volume-expand.go, glusterd2/commands/volumes/volume-info.go, glusterd2/commands/volumes/volume-list.go, glusterd2/commands/volumes/volume-option.go, glusterd2/commands/volumes/volume-start.go, glusterd2/commands/volumes/volume-status.go, glusterd2/commands/volumes/volume-stop.go, glusterd2/servers/rest/utils/utils.go, pkg/api/errors.go, pkg/restclient/common.go, plugins/bitrot/rest.go, plugins/device/rest.go, plugins/events/rest.go, plugins/georeplication/rest.go, plugins/glustershd/rest.go, plugins/quota/rest.go
* Remove having to specify default error code. It is made implicit
instead. This removes some of the code clutter.
* Support returning multiple errors in a single API response.
Although this will be rarely used, introducing the provision in API
right now is better than later.
* Allow callers to pass both string and error types.
* Introduce a error code map which maps error codes (integers) to their
brief textual description.
=> Simplify SendHTTPError()

e2e/config/1.toml, e2e/config/2.toml, e2e/config/3.toml, e2e/config/4.toml, glusterd2/brick/glusterfsd.go, glusterd2/config.go, glusterd2/main.go, plugins/bitrot/bitd.go, plugins/bitrot/scrubd.go, plugins/georeplication/gsyncd.go, plugins/georeplication/rest.go, plugins/glustershd/glustershd.go, plugins/quota/quotad.go
...except for the tests.
Rundir should be in a place like /var/run which doesn't persist across
reboots. Further some socket files and pid files were in '/var/run' and
few others in '/var/run/gluster'. With this change, everything goes into
the same rundir.
See this bug and fix for some historical context:
https://bugzilla.redhat.com/show_bug.cgi?id=1258561
Reference:
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
=> Default rundir to /var/run/gluster

glusterd2/config.go, glusterd2/main.go
Based on Kaushal's comment
https://github.com/gluster/glusterd2/issues/586#issuecomment-372268063
logging is reinitialized if it is different than command line arguments.
Fixes: #586
=> re-initialize logging after parsing config file

glusterd2/commands/volumes/brickutils.go, glusterd2/commands/volumes/common.go, glusterd2/commands/volumes/volume-create-disperse.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-create_test.go, glusterd2/commands/volumes/volume-option.go, glusterd2/transaction/context.go, glusterd2/volume/store-utils.go
* Move disperse related code and txn code to its own files.
* Move volume create validation and volinfo creation into a step func
which will be executed under lock. Updated issue #510 
* Slightly simplify validation of incoming request.
* Log failures inside txn.Get and txn.Set
* Include more info in errors returned at some places
=> Refactor volume create and other minor fixes

e2e/georep_test.go, glustercli/cmd/georep.go, plugins/georeplication/api/req.go, plugins/georeplication/api/resp.go, plugins/georeplication/events.go, plugins/georeplication/rest.go, plugins/georeplication/store-utils.go, plugins/georeplication/transactions.go
Made changes for GeorepRemoteHostReq, GeorepRemoteHost, GeorepWorker, GeorepSSHPublicKey
=> Using PeerID instead of NodeID

glusterd2/commands/volumes/bricks-status.go
Currently there is an issue with the output of volume status CLI command.
Steps To Reproduce :- 
1- Create a volume using volume create API or CLI command
2- Start the volume using API or CLI
3- Run the command "glustercli volume status <volname>"
Lets say the above created volume has 2 bricks "/brickpath1/brick1" and "/brickpath2/brick2" 
Then the volume status command should display output in form of a table with bricks column as follows 
Expected Output - 
PATH
/brickpath1/brick1
/brickpath2/brick2
But currently the  Output is as follows -
PATH
/brickpath2/brick2
/brickpath2/brick2
This PR resolves the above issue.
=> Error in Volume Status CLI Command Output.

glusterd2/commands/global/setglobaloptions.go, glusterd2/commands/peers/addpeer.go, glusterd2/commands/peers/editpeer.go, glusterd2/commands/volumes/optiongroup-create.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-expand.go, glusterd2/commands/volumes/volume-option.go, glusterd2/commands/volumes/volume-statedump.go, plugins/device/rest.go, plugins/events/rest.go, plugins/georeplication/rest.go
Fixes [#611](https://github.com/gluster/glusterd2/issues/611).
Return Status Code 400(Bad Request) instead of 422(unprocessable entity) whenever JSON Parsing fails.
=> Return 400(Bad Request) instead of 422(unprocessable entity)

glusterd2/xlator/global.go
This re-introduces most of code from the following commit:
bd97f9e70e01ec9d4b55d2aef2f220ef386ba462
Closes #666
=> xlator .so loading: gracefully handle panic (again)

e2e/peer_ops_test.go, e2e/utils_test.go, e2e/volume_ops_test.go
* Bumped up sleep at two places hoping that it'll reduce chances of
failure. Elastic etcd almost never works reliably on my machine :(
* Tear down cluster will now kill daemons spawned by glusterd2.
=> e2e: Minor fixes

pkg/utils/statedump.go
added return if writes statedump information to a file fails.
=> pkgs:utils added return if a write to file fails.

glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-create_test.go, glusterd2/volume/struct.go, glusterd2/volume/volume-utils.go, pkg/api/volume_req.go, pkg/api/volume_resp.go
Deals with [#462](https://github.com/gluster/glusterd2/issues/462)
Add Metadata as a new field in volinfo which acts like a dictionary and populate it during volume create.
=> Provide an option to set Metadata in volumes

e2e/config/1.toml, e2e/config/2.toml, e2e/config/3.toml, e2e/config/4.toml, e2e/main_test.go, e2e/utils_test.go
Previously, e2e tests were hard-coding the base workdir in
the main_test.go file and in the config toml files. This change
centralizes the base path in a top-level variable and makes
it possible to specify custom values for the workdir. This
can be useful if /tmp is inappropriate for this task on a
particular system or if multiple e2e tests are to be run in
parallel so that the caller may specify unique paths for
each test.
The toml files are adjusted to contain relative paths.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
=> e2e: make a central, configurable, base workdir

e2e/volume_ops_test.go, glusterd2/xlator/load.go
Which is not very portable and may not be widely available,
esp. in environments like containers etc.
=> avoid using which command as it is not always available

glustercli/cmd/volume-statedump.go
Usage:
```sh
$ glustercli volume statedump <volname>
$ glustercli volume statedump <volname> --quotad
$ glustercli volume statedump <volname> --client <ip>:<pid>
```
Updates #642
=>  Add CLI support for volume statedump

e2e/volume_ops_test.go
Instead of dropping the fake volume dirs into /tmp directly
(or whatever the os tmpdir happens to be)
locate them under the base workdir. This causes them to be
cleaned up & managed along with the glusterd2 process working dirs.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
=> e2e: move volume tmp dirs under base workdir

glusterd2/commands/volumes/volume-option.go, glusterd2/transaction/lock.go, glusterd2/transaction/step.go, glusterd2/transaction/transaction.go, glusterd2/xlator/actors.go, glusterd2/xlator/xlator.go
...that xlators can hook into to perform some custom action on nodes
that make up the volume. Actions can be something like starting or
stopping a daemon.
Closes #664 
=> Provide actors/hooks for volume set operation

doc/development-guide.md
updated development-guide to specify external ETCD URL 
etcdendpoints is the key in glusterd2.toml for external ETCD URL
=> updated key for specifing external etcd URL

glusterd2/commands/volumes/commands.go, glusterd2/commands/volumes/volume-reset.go, glusterd2/volume/store-utils.go, glusterd2/xlator/options/options.go, pkg/api/volume_req.go
Volume reset replaces the existing value of an option key with
the new value.
=> Updates #456: Add Volume Reset Rest API

glusterd2/servers/rest/rest.go
interchanged  Recover and Expvar handlers position in the rest server
=> recover as the first middleware handler in rest server

pkg/restclient/common.go
...that was set to 3 seconds. ResponseHeaderTimeout specifies the amount
of time to wait for a server's response headers after fully writing the
request. This time does not include the time to read the response body.
Instead, set 'Timeout' field of http.Client to 30s which includes TCP
connection time and also time taken to read the response body.
Regardless of how many nodes (even 100s) make up a volume, 30 seconds
is a large enough timeout for completion of a request.
Note:
* We can expose --timeout as a CLI option in future if deemed required.
* We may also introduce async APIs for long running tasks such as
dynamic volume provisioning.
Closes #750 
=> Remove ResponseHeaderTimeout

Makefile
I tried to run 'make test' out of a clean repo and it failed
due to missing source files that were being generated as
part of the build. I have tweaked the Makefile so that a
new target 'generated' is a prerequisite for the tests and
build.
In the future we might consider switching to calling something
like 'go generate' here. But I'm trying to keep this change
small.
=> makefile: support generating sources via a standalone target

glusterd2/commands/peers/addpeer.go, glusterd2/peer/self.go, pkg/utils/peerutils.go
store peer addresses provided during peer add in ETCD.
if peer address already present in the store
update configuration on startup
this allows the users to use peer address
provided during peer add, for any other
operations(ex:- volume create,expand)
Fixes: #725 
Fixes: #758
Fixes: #724
Fixes: #721
=> Store peer address provided during peer add 

glusterd2/gdctx/context.go, glusterd2/middleware/request_id.go, glusterd2/middleware/request_logging.go, glusterd2/transaction/lock.go
Request logger was eariler being set to logrus.Entry type.
With this change, request logger is set to logrus.FieldLogger which is
an interface and logrus.Entry implements this interface. Further,
renamed variables to make difference between logger and entry more
clear.
This change also fixes a crash in transaction.CreateLockFuncs() which
occurs when logger is nil. Logger will be nil if context passed is
not derived from the REST request.
=> Set request logger to logrus.FieldLogger interface type

glusterd2/commands/peers/editpeer.go, glusterd2/commands/volumes/bricks-status.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-delete.go, glusterd2/commands/volumes/volume-edit.go, glusterd2/commands/volumes/volume-expand.go, glusterd2/commands/volumes/volume-option.go, glusterd2/commands/volumes/volume-reset.go, glusterd2/commands/volumes/volume-start.go, glusterd2/commands/volumes/volume-statedump.go, glusterd2/commands/volumes/volume-stop.go, glusterd2/transaction/lock.go, glusterd2/transaction/transaction.go, plugins/bitrot/rest.go, plugins/device/rest.go, plugins/georeplication/rest.go, plugins/glustershd/rest.go, plugins/quota/rest.go
This PR introduces a new NewTxnWithLocks function and a (*Txn).Lock method.
With this change, support for having locking as part of transaction steps has
been removed. Doing locks within steps could lead to TOCTOU race problems, as
in several cases, volinfos would be fetched/modified in the rest handler before
the transaction steps were performed.
@prashanthpai started doing changes with regards to the TOCTOU problem with
them.
With this change, users now need to explicitly create a transaction and obtain
locks on the required IDs before fetching/modifying stored data in the rest
handlers.
The rest of the transaction framework remains as is.
=> New transaction locking mechanisms

extras/nightly-rpms.sh
Using `mock` on CentOS/Fedora as root resolves it to /sbin/mock, which
only works if a mock user has been setup. Forcing the use of
/usr/bin/mock makes this work always.
=> nightly-rpms: Use /usr/bin/mock instead of mock

e2e/volume_ops_test.go, glustercli/cmd/volume-create.go, glustercli/cmd/volume.go, glusterd2/brick/types.go, glusterd2/brick/validation.go, glusterd2/commands/volumes/common.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-expand-txn.go, glusterd2/commands/volumes/volume-expand.go, pkg/api/volume_req.go, pkg/errors/error.go
added functionality to expose flags in volume create and expand
added an additional flag to create brick dir if it's not exists
exposed flags for volume creation and expansion in glustercli
added e2e test cases for flags in
volume create and volume expand
Fixes #751
Fixes #675
=> added functionality to expose flags in volume create and expand

glustercli/cmd/peer.go
When there are multiple peer addresses,
display each one in a separate line.
=> Display peer addresses in new line

glusterd2/commands/peers/peer-rpc-svc.go
When a peer gets a request to join a cluster, only the global events
listener was being shutdown, and not the entire events framework. This
resulted in the liveness watcher to continue running which became an
infinite loop because the etcd watch channel won't block.
```go
wch := store.Store.Watch(...)
for {
select {
case resp := <-wch: // this wouldn't block
...
case <-l.stopCh:
return
}
}
```
This change will ensure that the entire events framework including
the liveness watcher shuts down before the store access shuts down.
Closes #817 
=> Fix 100% CPU usage after peer add

glusterd2/commands/volumes/common.go, glusterd2/commands/volumes/volume-option.go, plugins/bitrot/rest.go
In case of bitrot enable transaction failure, we need to revert back the updated volume
information.
Updates #815 
=> added undo function  to revert back volinfo changes

e2e/main_test.go, e2e/smartvol_ops_test.go, e2e/utils_test.go, glustercli/cmd/utils.go, glustercli/cmd/volume-create.go, glusterd2/commands/volumes/volume-create.go, glusterd2/plugin/plugins.go, glusterd2/volume/volume-utils.go, pkg/api/bricktype.go, pkg/restclient/volume.go, plugins/device/transaction.go, plugins/smartvol/api/req_resp.go, plugins/smartvol/bricksplanner/planner.go, plugins/smartvol/bricksplanner/subvoltype_disperse.go, plugins/smartvol/bricksplanner/subvoltype_distribute.go, plugins/smartvol/bricksplanner/subvoltype_replicate.go, plugins/smartvol/bricksplanner/utils.go, plugins/smartvol/init.go, plugins/smartvol/rest.go, plugins/smartvol/transactions.go
With this feature, Gluster can choose the bricks automatically based
on the given Volume size.
Gluster will not assume the list of devices available in each
peer. Register the devices which can be used by Gluster for
provisioning the bricks.
glustercli device add <peerid> <device>
Once the devices are registered, Gluster Volume can be created using,
glustercli volume create gv1 --size 1G
To create distributed replicate Volume, specify the distribute count as below.
glustercli volume create gv1 --size 1G --replica 3 --distribute 2
Options available with this command are,
--size                    (required) Size of Volume
--distribute              (optional) Distribute count, Default value is 1
--replica                 (optional) Replica count(Possible values: 2, 3),
Default value is 0 …
=> Intelligent Volume Provisioning

glusterd2/commands/volumes/volume-create-txn.go, glusterd2/transaction/context.go, glusterd2/transaction/transaction.go
Use expvar package to add metrics about how many times the txn context
accesses store for get and commit (etcd put txn) operations. This
metric is stored on a per instance basis and can be seen via /statedump
API.
Example:
```sh
$ curl -s -X GET http://127.0.0.1:23007/statedump | grep txn
"txn": {"txn_ctx_store_get": 5},
$ curl -s -X GET http://127.0.0.1:24007/statedump | grep txn
"txn": {"initiated_txn_in_progress": 0, "initiated_txn_success": 4, "txn_ctx_store_commit": 12, "txn_ctx_store_get": 8},
$ curl -s -X GET http://127.0.0.1:25007/statedump | grep txn
"txn": {"txn_ctx_store_get": 5},
```
The above example is from a run (create,start,stop,delete volume) on a
3 peer cluster. The second peer (127.0.0.1:24007) is the initiator node
which does most of puts to etcd.
Signed-off-by: …
=> txn context: Add store access counters

e2e/utils_test.go, glusterd2/middleware/request_id.go, glusterd2/servers/rest/utils/utils.go, glusterd2/transaction/context.go, glusterd2/transaction/rpc-service.go, glusterd2/transaction/step.go, glusterd2/transaction/transaction.go, pkg/api/errors.go, pkg/restclient/common.go
The txn framework now returns detailed error to the client i.e which step
failed on which peer and with what error.
Bonus cleanup and fix (separate commits) included in the PR:
* txn context: Reuse newCtx() when unmarshalling.
* Log txn step failure on remote node as Error.
* Ensure that response headers are always sent to client in all responses.
* txn: Remove Cleanup() and use Done()
=> txn: Return detailed error to client

glustercli/cmd/root.go
=> Fix typo in glustercli/cmd/root.go

e2e/georep_test.go, e2e/glustershd_test.go, e2e/quota_enable.go, e2e/restart_test.go, e2e/smartvol_ops_test.go, e2e/utils_test.go
The `localstatedir` from config file contained relative path which was
not being converted to absolute path before passing as command line
argument to glusterd2. This caused localstatedirs of different glusterd2
instances to be nested under one another. 
Closes #878 
Other minor fixes/cleanups:
* Ensure all tests use isolated temp dirs based on the name of the test
* Remove duplicate call to cleanupAllGlusterPvs()
* Unexport `UpdateDirs()` as it was is only used internally.
=> e2e: Fix temp dirs used by tests

pkg/restclient/events.go
API to list gluster events  was not there implemented in rest-client, added rest-client API for list gluster events to cover the e2e test cases 
=> events: rest client API to list gluster events

e2e/volume_ops_test.go, glusterd2/commands/volumes/volume-expand-txn.go
If Replica count is increased during add brick then new bricks will
be added to existing sub volumes, If replica count is not changed then
new bricks should be added as new sub volume. Default behavior was
adding bricks to existing sub volumes. With this PR default behavior is
changed to add new sub volume.
Fixes: #819
=> add-brick: Fix issue while add brick without changing replica count

e2e/volume_ops_test.go, glusterd2/brick/types.go, glusterd2/brick/validation.go, glusterd2/commands/volumes/common.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-expand-txn.go, glusterd2/volume/store-utils.go
During volume create and volume expand, when `--force` or `--reuse-bricks` is
used, specifying a brick used by a different volume was being allowed. Bricks
belonging to a different active volume shouldn't be reused in any case.
This is enforced by:
* Checking volume id xattr on proposed brick path against volume id of other all
available volumes.
* Checking if proposed brick path is a nested subdir of another active brick on
the peer.
Closes #931 
=> Prevent reusing bricks belonging to different volume

doc/quick-start-user-guide.md, e2e/bitrot_test.go, e2e/config/1.toml, e2e/config/2.toml, e2e/config/3.toml, e2e/config/4.toml, e2e/georep_test.go, e2e/glustershd_test.go, e2e/main_test.go, e2e/quota_enable.go, e2e/restapi_auth_test.go, e2e/restart_test.go, e2e/smartvol_ops_test.go, e2e/utils_test.go, e2e/volume_ops_test.go, e2e/webhook_test.go, glusterd2/config.go, glusterd2/gdctx/global.go, glusterd2/gdctx/global_test.go, glusterd2/main.go, glusterd2/middleware/auth_test.go, glusterd2/volgen/config.go, scripts/gen-gd2conf.sh
For all practical purposes, in real usage and in tests, the configurable
paths `workdir` and `localstatedir` are set to the same directory which
defaults to `/var/lib/glusterd2` or `/user/local/var/lib/glusterd2`
Unlike glusterd1, glusterd2 does not daemonize itself. The working
directory of the process can be meaningfully set to either current
working directory from where glusterd2 process is started or to
`localstatedir` where glusterd2 stores all its data. We choose the
latter.
This change also reduces ambiguity for users and one less thing to
configure.
Closes #888 
=> Remove 'workdir' config in favour of 'localstatedir'

glusterd2/commands/volumes/common.go, glusterd2/commands/volumes/volume-option.go, glusterd2/commands/volumes/volume-reset.go
Allow to set options on volumes if volume state is stopped or created, don't start daemons.
if volume state is started then set options on volume and also start daemons.
Fixes: #934 
=> volume-options: dont start daemons if volume state is  stopped or created

Makefile
The current all/build targets do quite a bit more than compile
the golang binaries. This change adds a new target "binaries"
that builds the server and cli binaries.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
=> makefile: add a target that only builds the binaries

e2e/bitrot_test.go, e2e/utils_test.go, e2e/volume_ops_test.go, e2e/webhook_test.go
Add a helper function for tests that need unique test dirs that
creates test directories like /[base]/[testname]/[unique].
Fixes #927
Signed-off-by: John Mulligan <jmulligan@redhat.com>
=> e2e: establish a common approach to creating per-test temp dirs

glustercli/cmd/volume.go
Partial: #503 
**sample output**
```
[root@dhcp42-235 glusterd2]# ./build/glustercli --endpoints=http://10.70.43.235:24009 volume get test1 all --modified --basic
+---------------------+----------+-------+---------------+--------------+
|        NAME         | MODIFIED | VALUE | DEFAULT VALUE | OPTION LEVEL |
+---------------------+----------+-------+---------------+--------------+
| changelog.changelog | yes      | on    | off           | Basic        |
+---------------------+----------+-------+---------------+--------------+
[root@dhcp42-235 glusterd2]# ./build/glustercli --endpoints=http://10.70.43.235:24009 volume get test1 all --modified --advanced
+----------------------------+----------+--------------------------------------+-----------------+--------------+
|            NAME …
```
=> Filter Volume options based on CLI flags

glusterd2/gdctx/global.go
if the gluster group is not present on the
a system where glusterd2 is supposed to run,
set Current user GID as UID for auth file
=> change group 

glusterd2/commands/volumes/grouped-options.go, glusterd2/commands/volumes/volume-option.go, glusterd2/xlator/global.go, glusterd2/xlator/load.go, glusterd2/xlator/options/options.go, glusterd2/xlator/options/utils.go
This change enables setting up TLS for client to bricks communication.
Unlike glusterd1 which requires two separate options - `client.ssl` and
`server.ssl` to be turned on, turning TLS on for a volume in glusterd2
is a single volume set operation. TLS can be enabled for a volume as
follows:
$ glustercli volume set <volname> --advanced tls on
To achieve this, when xlator shared ojects are loaded during startup,
options present in transport layer (socket.so and rdma.so) are injected
into list of options loaded from protocol layer (server.so and
client.so). The client and brick volfile expects the transport options
to be in client and server xlator sections.
This PR also tests that client authorization works as expected which can be used as follows:
```sh
$ glustercli volume set test …
```
=>  Add TLS support for client-bricks communication

glusterd2/commands/volumes/volume-start.go, glusterd2/commands/volumes/volume-stop.go, glusterd2/volgen/volfile_bitd.go, glusterd2/volgen/volfile_quotad.go, glusterd2/volgen/volfile_scrub.go, glusterd2/volgen/volfile_shd.go
Cluster level volfiles should not contain the information about Stopped
Volumes. Added checks for the same while generating Cluster level
volfiles. But when Volume starts, these volfiles will not contain the
started Volume's info. iTo address this issue added Volfiles re-generation
after Volume Stop and Start.
Closes: #1005
=> Regenerating Volfiles on Volume Start and Stop

e2e/config/1.toml, e2e/config/2.toml, e2e/config/3.toml, e2e/config/4.toml, glustercli/cmd/root.go, glusterd2.toml.example
With this change, secret is taken by CLI in following order of precedence (highest to lowest):
```
--secret
--secret-file
GLUSTERD2_AUTH_SECRET (environment variable)
--secret-file (default path)
```    
Other changes:
* The command-line flag `--authfile` has been renamed to `--secret-file` to be consistent with the flag `--secret`.
* This change also illustrates default value of restauth in sample config and removes examples from e2e test configurations.
Closes #994
=> cli: Add support for reading secret from ENV

glusterd2/volgen/clustergraph.go
`option afr-pending-xattr` will contain list of xattrs names which will
be used to find bricks for which heal is pending. With this PR,
thin-arbiter brick id also added to the `afr-pending-xattr` list.
Known issue: Brick index needs to be persisted which is tracked here #925
Closes: #1006
=> Thin arbiter brick for afr-pending-xattr list

glustercli/cmd/common.go, glustercli/cmd/root.go, pkg/restclient/common.go
The client timeout is now configurable at the restclient layer and also
in the CLI. The client timeout defaults to 30 seconds in both restclient
and CLI.
Timeout can be configured in:
* restclient using SetTimeout() API.
* CLI using --timeout command line flag.
This client timeout is the overall timeout which includes the time taken
from setting up TCP connection till client finishes reading the response
body from glusterd2.
Closes #1027 
=> cli/restclient: Make client timeout configurable

glusterd2/volgen/volfile_brick.go
Fixes [#1038](https://github.com/gluster/glusterd2/issues/1038)
Change ordering of sdfs and io-stats in brick volfile.
=> Xlator mismatch in brick volfile

e2e/smartvol_ops_test.go, glustercli/cmd/volume-create.go, glusterd2/bricksplanner/subvoltype_replicate.go, glusterd2/commands/volumes/volume-create-txn.go
Change syntax for creation of arbiter volumes from:
`replica 3 arbiter `
to
`replica 2 arbiter 1`
Closes #515 
=> arbiter: Support replica 2 arbiter 1 usage

glusterd2/commands/volumes/volume-list.go
avoid sending ```200 OK``` if get volume fails from ETCD
=> added missing return 

glustercli/cmd/common.go
If last Error Response is nil, then calling failure function will cause
segmentation fault error
Fixes #1115
=> cli: Valiate Last Error Response in failure function of GlusterCli

glusterd2/store/store.go, glusterd2/transaction/context.go
...so that we can quickly know how many etcd operations are invoked
in a particular glusterd2 volume operation.
These expvar metrics can be seen using `/statedump` endpoint.
Updates https://github.com/gluster/glusterd2/issues/1079
=> etcd txn: Add expvar counters to wrappers

glusterd2/events/eventhandler.go, glusterd2/events/liveness.go
If we build GD2 by enabling the -race flag,
then On startup of GD2 it shows Data Race warning.
Fixes #715
=> Data Race While Starting GD2.

glusterd2/commands/peers/addpeer.go, glusterd2/commands/peers/editpeer.go, glusterd2/commands/snapshot/snapshot-clone.go, glusterd2/commands/snapshot/snapshot-create.go, glusterd2/commands/volumes/optiongroup-create.go, glusterd2/commands/volumes/volume-create.go, glusterd2/servers/rest/utils/utils.go, pkg/restclient/device.go, pkg/restclient/georep.go, pkg/restclient/volume.go, plugins/device/rest.go, plugins/georeplication/rest.go
When new resources such as peers, volumes and snapshots are created,
we return a `201 Created` response. The [HTTP RFC](https://tools.ietf.org/html/rfc7231#page-68) requires us to
return a `Location` header which contains an absolute or relative URL to
the newly created resource.
In cases where no new uniquely identifiable resource was created (georep),
we return a `200 OK` instead of `201 Created`
Other fix:
Return status `200 OK` and not `201 Created` in response to peer edit
request.
Fixes #1077
=> rest: Return 'Location' header in 201 Created responses

doc/development-guide.md
With respect to https://github.com/gluster/glusterd2/pull/1123. Using golang 1.9 or higher instead of 1.8. @prashanthpai Please check if we need to make changes in any other documentation.
=> Updating development guide to use golang version 1.9

glusterd2/volume/volume-utils.go
In my machine, `/var/run` is symlinked to `/run`. Snapshot bricks are
mounted in `/var/run` but `df` or `mount` output shows `/run`.
Snapshot clone fails with following error
Transaction step snap-clone.Validate failed on peer \
4e646eb6-0f51-4385-9892-a3a4ec7b1a67 with error: \
mount point not found
This PR fixes the issue by comparing realpath with the mount command
output.
=> Fix snapshot clone issue if snap mount dir is symlinked

doc/index.md
Link for REST API Reference page is not working.
Signed-off-by: Ankush Behl <cloudbehl@gmail.com>
=> [Fix] REST API Reference link

glusterd2/commands/peers/errors.go, glusterd2/commands/peers/peer-rpc-svc.go
during peer add, if the node is not able to connect to the store(ETCD).
return error message saying failed to connect to the store.
Fixes: #1045 
=> return an error when failed to connect to the store

glusterd2/bricksplanner/planner.go, glusterd2/commands/snapshot/snapshot-clone.go, glusterd2/commands/snapshot/snapshot-create.go, glusterd2/commands/volumes/volume-smartvol-txn.go, glusterd2/utils/mount.go
- For auto provisioned volumes, Changed `Brick.MountInfo.Mountdir`
to store only brick directory path after mount root(Similar to
Snapshot bricks info)
- Added/Changed LV and TP names to match one naming convention(As
described below)
- Auto provisioned bricks mount directory changed to
`<rundir>/glusterd2/` similar to snapshot bricks
On Volume create (Example: Volume name = gv1)
- Brick Path: `/var/run/glusterd2/bricks/gv1/subvol1/brick1/brick`
- Brick Mountroot: `/var/run/glusterd2/bricks/gv1/subvol1/brick1`
- Thinpool Name: `tp_gv1_s1_b1`
- LV Name: `brick_gv1_s1_b1`
On Snapshot create (Example: Snapshot name = snap1, volume name = gv1)
- Brick Path: `/var/run/glusterd2/snaps/snap1/gv1/subvol1/brick1/brick`
- Brick Mountroot: `/var/run/glusterd2/snaps/snap1/gv1/subvol1/brick1`
- …
=> Uniform Mountdir, Brick Paths and Device names

glusterd2/commands/snapshot/snapshot-create.go
we need to initialize map and slice to avoid displaying
as a `null` value in JSON response
Fixes: #1180 
=> snapshot: fix displaying null value in JSON response

glusterd2/commands/volumes/volume-create.go, glusterd2/transaction/rpc-service.go, glusterd2/transaction/step.go
Add attributes like request ID, volume name, volume size to volume create
tracing spans. This allows traces to be filtered based on the attribute
specified on the tracing UI. This will be very helpful when dealing with
multiple traces during debugging.
closes #1185
=> tracing: Add attributes to volume create spans to enable trace filtering.

glusterd2/gdctx/id.go, glusterd2/gdctx/id_test.go
This is an extension to b8f9625, which makes it much easier to provision
and deploy GD2 clusters in a K8S.
With this patch GD2 reads GD2_PEER_ID and GD2_CLUSTER_ID from the
environment if available, and saved into LOCALSTATEDIR/uuid.toml.
If both environment variables and the uuid file have IDs, preference is
given to the environment variables, over the uuid file.
Closes #1113
=> glusterd2: Support setting Peer and Cluster IDs from the environment

e2e/snapshot_ops_test.go, e2e/utils_test.go, e2e/volume_ops_test.go
..as `mount.glusterfs` utility might be installed in non-standard
location in test environments.
Besides, mounts in real code (volume status) already uses the binary
to mount and not the mount utility script.
=> Use glusterfs binary to mount

glusterd2/middleware/auth.go
Ping is required to check glusterd2
is running or not.
endpoints will list all the URL served by glusterd2
this should not require any authentication.
Fixes: #1200
=> Disable rest authentication for few URL's like /ping, /endpoints

pkg/restclient/common.go, pkg/restclient/common_test.go
applying tlsconfig to existing http.Client instead of
creating a new one.
=> restclient: applying tlsconfig to existing client Transport

Makefile
=> populate vendor/ from Gopkg.lock without updating it first

glusterd2/servers/rest/rest.go
We should read tls version from handshake layer not from the record layer.
It is the Handshake layer version number that is important.
=> gd2: fixed tlsmatcher to be used to multiplex tls connection

e2e/glustershd_test.go, e2e/lvmtest/lvmtest.go, e2e/process_utils_test.go, e2e/snapshot_ops_test.go, e2e/utils_test.go, e2e/volume_ops_test.go, glusterd2/commands/peers/deletepeer.go, glusterd2/commands/volumes/volume-smartvol-txn.go, plugins/device/deviceutils/utils.go
Contains a bunch of small code changes (not really fixes) that help debugging
seen failures or mitigate some of them:
* client.LeaveCluster: Return actual error to client
* e2e: Use http client with timeout and adjust wait time
* Use syscall to unmount
* e2e: Return error if auth secret file cannot be read
Updates https://github.com/gluster/glusterd2/issues/1220
Updates https://github.com/gluster/glusterd2/issues/1222
=> gd2 smoke: Improve debuggability of few e2e failures

glustercli/cmd/volume.go
`glustercli volume status` does not display any message if no volume exist.
```
[root@localhost build]# ./glustercli volume status
[root@localhost build]
```
**Expected:**
```
[root@localhost build]# ./glustercli volume status
No volumes found
[root@localhost build]#
```
=> Glustercli : Displaying volumes not found message if no volume exists

pkg/restclient/common.go, pkg/restclient/roundtrippers.go
A DebugWrapper will be helpful in debugging
restclient calls. To enable debugging we
need to pass `--loglevel` flag in glustercli
as debug
For Example, glustercli peer list --loglevel=debug
It will dump each outgoing request in
its HTTP/1.x wire representation and also It will
dump the received response in its HTTP/1.x wire
representation.
=> restclient: added debug wrapper for debugging restclient calls.

glusterd2/commands/peers/deletepeer.go, glusterd2/commands/peers/peer-rpc-svc.go, glusterd2/commands/volumes/volume-list.go, glusterd2/store/store.go, glusterd2/utils/mount.go, glusterd2/volgen/generate.go, glusterd2/volume/store-utils.go, glusterd2/volume/volume-utils.go, plugins/bitrot/transactions.go, plugins/quota/actor.go
Add instrumentation to trace volume list operation. Add the count of the
number of volumes listed by the command as an attribute in the top level
span of the trace.
Closes #1196
=> Tracing: Trace volume list operation

glusterd2/main.go, pkg/utils/statedump.go, pkg/utils/statedump_test.go, plugins/georeplication/init.go
The unit test `TestWriteStatedump` uses a filename derived from current
timestamp and the actual code (`WriteStatedump`) being tested also uses
filename of the same pattern but that one may have another timestamp as
that code executes slightly later. Hence, it can so happen that the file
name written by `WriteStatedump()` is different than the filename expected
by the test. As these two timestamps are at seconds level granularity,
we didn't see it fail earlier.
This change modifies the test to look for a pattern that resembles
statedump file.
=> Fix TestWriteStatedump test

extras/nightly-container/provision.yml, extras/rpms/glusterd2.spec, extras/systemd/glusterd2.service, version/version.go
This PR enables a few settings in the glusterd2.service systemd unit to enable
better support for environment variables in containers.
Also, prepares for v5.0.0-rc0 tagging.
=> Better support for environment variables in container image

glusterd2/brick/types.go, glusterd2/commands/snapshot/snapshot-create.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-create_test.go, glusterd2/commands/volumes/volume-delete.go, glusterd2/commands/volumes/volume-expand-txn.go, glusterd2/utils/mount.go, glusterd2/volume/struct.go, glusterd2/volume/volume-utils.go, glusterd2/volume/volume_test.go
Brick should be able to identify whether it is auto provisioned
or not. This is required for cases like
* Mounting of a brick in glusterd restart
* Umounting of a brick on volume stop/delete
* delete brick directoroy when volume is deleted
* delete vg/lv during volume delete
* To smoothly handle replace brick/reset brick on auto provisioned bricks
=> Volume: Add auto provision flag to brick info

e2e/smartvol_ops_test.go, e2e/volume_ops_test.go, glustercli/cmd/volume-create.go, glusterd2/commands/volumes/volume-create.go, glusterd2/volume/volume-utils.go
- CSI driver also passes Volume name to Volume create API
- Mandatory Volume name also helps to ignore
duplicate(accidental/network failure) Volume create
API requests(Discussed here
https://github.com/gluster/glusterd2/issues/919#issuecomment-401022413)
- Applications can generate name and can pass to API, not much benefit
of auto generating name from glusterd2
- Supporting both the syntax in CLI adds confusion
=> Make Volume name mandatory in Volume create request

e2e/glustershd_test.go, e2e/snapshot_ops_test.go, e2e/volume_ops_test.go
remove code duplication in volume_ops_test
call checkFuseAvailable from utils package to avoid code duplication.
after volume mount even if some of the operations fail on the volume. we should umount the volume
calling umount in defer immediately after the volume mount will ensure to call the umount if some operation
fails.
Partial: #1235 
=> fix issue in e2e 

test/020-gofmt.sh
`gofmt` is returning zero even if format is not proper. Instead it
returns list of files which are not properly formatted.
This issue in golang repo suggested to use `test -z` for the same
https://github.com/golang/go/issues/24230
=> Fix issue while doing `gofmt` tests

glusterd2/xlator/load.go, pkg/logging/logging.go
The benign log messages logged by `net/rpc` package's `server.Register()`
is very annoying. The enhancement introduced by bdaa2c9 (PR #1237)
amplified this already excessive logging.
Logging by code in standard library is now disabled. Earlier it was
being redirected to logrus's io.Writer.
=>  log: Turn off standard library logging

glustercli/cmd/snapshot-info.go, glustercli/cmd/utils.go, glustercli/cmd/utils_test.go, glustercli/cmd/volume.go, glusterd2/commands/snapshot/snapshot-create.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/volume/struct.go, glusterd2/volume/volume-utils.go, pkg/api/volume_resp.go
this command is used to display the status of all the volumes.
Updates #1136 
=> glusterd2: gluster volume info to display the capacity of the volume.

e2e/glustershd_test.go, e2e/quota_enable.go, e2e/volume_ops_test.go, glustercli/cmd/volume-create.go, glustercli/cmd/volume-set.go, glusterd2/commands/volumes/common.go, glusterd2/commands/volumes/optiongroup-create.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-option.go, pkg/api/volume_req.go
'--advanced' in the CLI and REST API during volume create doesn't intuitively
and clearly indicate that it's for the volume options. A new user may read this
as creation of an "advanced volume" which isn't true.
The flags have now been prepended with 'allow' in the fields of request structs.
The API has been renamed as 'allow-<type>-options'.
Also, created 'VolOptionFlags' struct for flags of options and embeded it in
all request structs.
Closes #1078 
=> Refactor flags/filters applied to set volume options

e2e/lvmtest/lvmtest.go, e2e/snapshot_ops_test.go, e2e/volume_ops_test.go, glustercli/cmd/utils_test.go, glusterd2/brick/types.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-list.go, glusterd2/gdctx/id.go, glusterd2/gdctx/id_test.go, glusterd2/main.go, glusterd2/servers/sunrpc/handshake_prog.go, pkg/utils/utils_test.go, plugins/glustershd/transactions.go
Current report:
https://goreportcard.com/report/github.com/gluster/glusterd2
* Fix typos reported by misspell tool.
* golint: Fix redundant returning of error.
* Fix ineffectual assignments detected by ineffassign.
Fixing gocyclo warnings needs more involved work to do it right
when we split long functions to smaller ones. That hasn't been
addressed in this PR.
=> Fix issues reported by Go Report Card

e2e/snapshot_ops_test.go, glusterd2/brick/types.go, glusterd2/bricksplanner/planner.go, glusterd2/commands/snapshot/snapshot-clone.go, glusterd2/commands/snapshot/snapshot-create.go, glusterd2/commands/snapshot/snapshot-deactivate.go, glusterd2/commands/snapshot/snapshot-delete.go, glusterd2/commands/snapshot/snapshot-restore.go, glusterd2/commands/volumes/volume-smartvol-txn.go, glusterd2/main.go, glusterd2/snapshot/snapshot-utils.go, glusterd2/snapshot/store-utils.go, glusterd2/utils/mount.go, glusterd2/volume/fs_utils.go, glusterd2/volume/struct.go, glusterd2/volume/volume-utils.go, pkg/api/volume_req.go, plugins/device/deviceutils/store-utils.go
Snapshot bricks should automatically mount upon a glusterd restart. Especially after glusterd restart, mount won't be existing on the machine. This PR will mount the snapshot bricks during a glusterd restart.
=> Snapshot auto mount bricks on glusterd restart 

glusterd2/commands/options/setclusteroptions.go, glusterd2/options/cluster.go, glusterd2/volume/fs_utils.go
* Take lock when setting/updating cluster option.
* Add support for custom validation function.
* Fix crash in GetClusterOption() due to nil pointer access.
The first consumer of these fixes and improvements shall be brick multiplexing.
Updates #219
=> Improve getting/setting cluster options

e2e/smartvol_ops_test.go, glustercli/cmd/volume-create.go, glusterd2/brick/validation.go, glusterd2/commands/volumes/common.go, glusterd2/middleware/auth.go, glusterd2/snapshot/lvm/lvm.go, glusterd2/xlator/load.go, pkg/api/brickutils.go, plugins/bitrot/validate.go, plugins/dht/validate.go
As mentioned in the error-handling section of [coding conventions](https://github.com/gluster/glusterd2/blob/master/doc/coding.md#error-handling) below:
```
* Error strings should not start with a capital letter.
```
This pull request does what #902 have done that set the first letter of error message to lowercase. Note that the names of struct definitions are already ignored, such as `BrickType`, etc.
Signed-off-by: imjoey <majunjiev@gmail.com>
=> Fix capitalized error message format.

glusterd2/store/config.go
The descriptions of the `--etcdcurls` and `--etcdpurls` flags are reversely assigned.
=> Fix mistaken command flag descriptions

extras/nightly-container/provision.yml
- Depends on rpm spec file PR
https://github.com/gluster/gluster-prometheus/pull/26
- Nightly rpm building is not yet setup
- Depends of environment variable related PR
https://github.com/gluster/gluster-prometheus/pull/66
=> Include gluster-prometheus-exporter rpm in glusterd2 container

extras/nightly-container/provision.yml
I had asked for the usage of the 'service' module to enable services in
the Ansible provisioner. Forgetting that 'service' module does not work
with Ansible-Buildah as systemd isn't running in the build container
(there is even a comment about this).
This commit changes back to using the 'command' module.
=> nightly-container: Use 'command' instead of 'service'

glusterd2/commands/volumes/volume-expand.go
Fixes [#1329](https://github.com/gluster/glusterd2/issues/1329)
Volume expand fails to start bricks when volume is in started state but works fine when volume is in Stopped/Created state
Fix - Brick Volfiles need to be generated beafore starting the bricks.
=> Volume expand fails to start bricks when volume is in started state

glustercli/cmd/utils.go, glustercli/cmd/utils_test.go
Earlier `humanReadable` function was accepting values in `MiB`
With PR #1326 default unit is changed to bytes.
=> Fix the Volume Capacity display in CLI

plugins/glustershd/rest.go
Change in format to run glfsheal to fetch heal info.
Previously it was -
glfsheal volname xml glusterd-sock <socket-filename.socket>
There might have been some new introductions on glusterfs side.
https://review.gluster.org/#/c/glusterfs/+/21501/
The new format is -
glfsheal volname --xml glusterd-sock <socket-filename.socket>
This should resolve the CI errors related to heal.
=> Changes in format to run glfsheal to get heal info.

glustercli/cmd/georep.go, glustercli/cmd/root.go, plugins/georeplication/gsyncd.go, plugins/georeplication/rest.go, plugins/georeplication/transactions.go
- gsyncd path defaulted to `/usr/libexec/glusterfs/gsyncd`
- Fixes remote REST API auth issues
- Workaround to make it work with marker xlator
=> geo-rep: Fixes for remote authentication and gsyncd path

plugins/device/deviceutils/store-utils.go
If a device exists with same name in different Peer, it is possible to
get the available size information of the device from different
Peer than getting information locally.
=> Volume expand: Consider peer id while checking available size

e2e/brickmux_test.go, glusterd2/brickmux/compat.go, glusterd2/brickmux/demultiplex.go, glusterd2/brickmux/multiplex.go, glusterd2/brickmux/option.go, glusterd2/brickmux/reconcile.go, glusterd2/brickmux/utils.go, glusterd2/commands/volumes/volume-start.go, glusterd2/commands/volumes/volume-stop.go, glusterd2/daemon/utils.go, glusterd2/main.go, glusterd2/pmap/pmap.go, glusterd2/pmap/registry.go, glusterd2/pmap/registry_test.go, glusterd2/pmap/rpc_prog.go
This PR adds support for multiple brick translator stacks running in
a single brick server process. Multiplexing is controlled by the
`cluster.brick-multiplex` global option. By default it's off, and
bricks are started in separate processes as before. If multiplexing is
enabled, then *compatible* bricks (those with the same volume options)
will be started in the same process.
Multiplexing and demultiplexing involves sending an RPC request from
glusterd2 to brick process.
**Pidfile and socket files:**
* Each multiplexed brick will have a separate pidfile (returned by
`PidFile()` method of `Daemon` interface).
* As multiplexed bricks will have only one server xlator, it will be
listening on only one Unix Domain Socket file. A hardlink to this
socketfile is created per multiplexed brick. …
=> Implement brick multiplexing

glusterd2/servers/sunrpc/server.go, pkg/sunrpc/servercodec.go
acceptLoop keeps a list of all sessions, and each session keeps a reference to the memory block allocated as a read buffer. This reference is there even if the session closes, so as long as acceptLoop runs, memory keeps growing. This should fix it by doing two things: 1) When session closes, remove the reference to the buffer. But that will still continue to leak sessions, because nothing removes elements from the session list. So, 2) remove the logic that keep track of sessions, instead, run two goroutines for each session, one to keep the session and run the server, and the other to terminate the first one when needed.
I don't have the infra to verify this, so let me know how it goes.
=> Fix #1321: remove session references

e2e/smartvol_ops_test.go
Since volume was not started, volume stop was unnecessarily placed in the e2e test case.
=> Removing volume stop from replace-brick e2e test case

doc/profiling.md, glusterd2/config.go, glusterd2/servers/rest/rest.go, glusterd2/utils/pprof.go
Currently CPU and memory/heap profiling are implemented.
Changes have been made to enabled them from the config file.
The output prof file is seen is /tmp/profile...
The output file has to be passed to the go tool pprof to read and
understand the bottleneck we are trying to resolve.
=> Implements profiling for GD2

e2e/brickmux_test.go, glusterd2/brickmux/compat.go, glusterd2/brickmux/multiplex.go, glusterd2/brickmux/option.go, glusterd2/options/cluster.go, glusterd2/pmap/pmap.go, glusterd2/pmap/registry.go, pkg/errors/error.go
Fixes [#1304](https://github.com/gluster/glusterd2/issues/1304)
Implement max-bricks-per-process cluster option for brick multiplexing.
=> Max-bricks-per-process option for brick multiplexing.

plugins/device/api/resp.go, plugins/device/deviceutils/store-utils.go, plugins/device/transaction.go
it will be user-friendly if we have total, free and used fields in device response.
total size= total size of the device.
free size= available size of the device for volume creation.
used size= space used for volume creation.
```
[root@dhcp43-209 build]# curl http://10.70.43.209:24007/v1/devices |python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   794  100   794    0     0   395k      0 --:--:-- --:--:-- --:--:--  775k
[
{
"device": "/dev/vdb",
"device-used": false,
"extent-size": 4194304,
"free-size": 0,
"peer-id": "335f3b47-cdc6-46ad-806e-6340f867c428",
"state": "enabled",
"total-size": 0,
"used-size": 0
},
{
"device": "/dev/vdc",
"device-used": false,
"extent-size": 4194304,
"free-size": …
```
=> Add total and used field to device response

glustercli/cmd/utils.go
we should be able to create volume size with
different formats like KB, Kib, Mb, MiB etc
Fixes: #1398
```
[root@dhcp43-209 build]# ./glustercli volume create size1 --size=20MB --replica=3 -v
size1 Volume created successfully
Volume ID:  b2693574-8489-4d4b-94ab-3564776d1cce
[root@dhcp43-209 build]# ./glustercli volume create size2 --size=20MiB --replica=3 -v
size2 Volume created successfully
Volume ID:  b1153478-4912-4481-a047-8d67258ab08c
[root@dhcp43-209 build]# ./glustercli volume create size3 --size=20M --replica=3 -v
size3 Volume created successfully
Volume ID:  8ac1c9a5-cc84-45ec-b382-eff17369d024
[root@dhcp43-209 build]# ./glustercli volume create size35 --size=20 --replica=3 -v
size35 Volume created successfully
Volume ID:  560da74f-b7cf-466c-994c-0f03ba07bb24
[root@dhcp43-209 …
```
=> add regex for different volume size format

glustercli/cmd/glustershd.go, glustercli/cmd/volume-create.go, glustercli/cmd/volume.go
add logging if there is an error in CLI, with the help of `-v` flag user should
be able to check the failure logs.
Fixes #1414
=> Add logging if there is an error in CLI

pkg/lvmutils/utils.go
`vgdisplay` command will be used during Volume create to update the
device size after each Volume Create. `lvs` command is used to check
number of LVs in a Thinpool before deleting the Thinpool. Added
readonly to both the commands to avoid lvm lock.
=> Avoid using lvm lock while using readonly commands

e2e/smartvol_ops_test.go, glusterd2/bricksplanner/planner.go
Auto provisioned volume does not validate the minimum brick size.
If the size is too small then the volume creation errors out.
The validation is done after the bricksize calculation.
Fixes: #1389
=> minimum brick size validation during Volume create

pkg/sunrpc/record.go
Sunrpc Read buffer was created by allocating `1MiB` each time when
client connects. Go can automatically expand the buffer when required
so now empty buffer is initialized.(`1MiB` per brick connect is `1GB`
for 1000 bricks)
=> Do not allocate memory manually while creating RPC buffer

glusterd2/store/store.go, glusterd2/transaction/lock.go, glusterd2/transactionv2/cleanuphandler/cleanup_handler.go, glusterd2/transactionv2/executor.go, glusterd2/transactionv2/transaction.go, glusterd2/transactionv2/txnmanager.go
- all cluster locks should be aquired before starting a txn.
We should acquire locks at the time of creating a txn.
- use namespaced etcd client for creating a etcd Session in
transaction.Lock and CleanupHandler
=> txn Lock: acquire cluster locks while creating a txn

glusterd2/commands/volumes/brick-replace-txn.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-expand-txn.go
Brick paths are generated while creating smart volume using volume
name, subvol number and brick number. So collision will not happen
when multiple smart volumes are created.
=> Skip local bricks path validation if auto provisioned volume

Gopkg.lock, Gopkg.toml, glusterd2/volume/fs_utils.go, pkg/restclient/block_volume.go, plugins/blockvolume/blockprovider/gluster-loopback/glusterloopback.go, plugins/blockvolume/init.go
Signed-off-by: Poornima G <pgurusid@redhat.com>
=> Add loopback block provider

e2e/smartvol_ops_loop_test.go, e2e/snapshot_ops_test.go, glustercli/cmd/device.go, glustercli/cmd/volume-create.go, glusterd2/brick/types.go, glusterd2/bricksplanner/planner.go, glusterd2/bricksplanner/utils.go, glusterd2/commands/snapshot/snapshot-clone.go, glusterd2/commands/snapshot/snapshot-create.go, glusterd2/commands/snapshot/snapshot-restore.go, glusterd2/commands/volumes/brick-replace-txn.go, glusterd2/commands/volumes/brick-replace.go, glusterd2/commands/volumes/volume-create-txn.go, glusterd2/commands/volumes/volume-create.go, glusterd2/commands/volumes/volume-smartvol-txn.go, glusterd2/volume/struct.go, glusterd2/volume/volume-utils.go, pkg/api/volume_req.go, pkg/api/volume_resp.go, pkg/errors/error.go, pkg/fsutils/utils.go, pkg/lvmutils/utils.go, pkg/restclient/device.go, plugins/device/api/req.go, plugins/device/api/resp.go, plugins/device/deviceutils/store-utils.go, plugins/device/rest.go, plugins/device/transaction.go
Register the Bricks hosting directory using,
```
glustercli device add <peerid> <path> --provisioner loop
```
Example:
```
glustercli device add 70d79c3f-e7af-43f6-8b65-05dff2423da1 \
/exports --provisioner loop
```
Now create the volume using,
```
glustercli volume create gv1 --size 1G \
--provisioner loop \
--replica 3
```
Fixes: #1418
=> Support for loopback bricks

glusterd2/transactionv2/engine.go, glusterd2/transactionv2/executor.go, glusterd2/transactionv2/tracingexecutor.go, glusterd2/transactionv2/transaction.go, glusterd2/transactionv2/txnmanager.go
If a peer restarts then it should check for pending
transactions and resume all the pending transaction.
=> transaction: resume txn if a peer restarts

glusterd2/middleware/tracing.go, glusterd2/servers/rest/rest.go, glusterd2/transaction/step.go, glusterd2/transactionv2/engine.go, glusterd2/transactionv2/executor.go, glusterd2/transactionv2/steptracing.go, glusterd2/transactionv2/tracingexecutor.go
Decouples tracing code from RunStepFuncLocally() func and
added a middleware which implements transaction.StepManager
to trace step funcs. This will provide a better trace
management and clean code.
=> tracing: refactor tracing code in transaction

glustercli/cmd/volume-create.go, glusterd2/volume/filters.go, glusterd2/volume/volume-utils.go, plugins/blockvolume/api/types.go, plugins/blockvolume/blockprovider/gluster-block/glusterblock.go, plugins/blockvolume/blockprovider/gluster-virtblock/gluster_virtblock.go, plugins/blockvolume/blockprovider/options.go, plugins/blockvolume/handlers.go, plugins/blockvolume/hostvol/hostvol_manager.go, plugins/blockvolume/hostvol/hostvol_opts.go, plugins/blockvolume/hostvol/utils.go, plugins/blockvolume/routes.go
With this the block volumes can be created on thin arbiter, shard volumes. 
Signed-off-by: Poornima G <pgurusid@redhat.com>
=> BlockVolume add extra arguments to create and reduce number of cluster locks

extras/rsyslog-container/Dockerfile, extras/rsyslog-container/README.md, extras/rsyslog-container/gd2.rulebase, extras/rsyslog-container/rsyslog.conf
This is a lightweight container based on Alpine Linux and run as a
sidecar container in a gcs cluster along with containers running gd2.
This is mainly used to parse gluster specific logs and normalize it for
elastic search. Right now only gd2 logs are parsed to some extent. For
this, an rsyslog configuration along with a rulebase file are included.
=> Add gluster-rsyslog Alpine container

glusterd2/pmap/registry.go, glusterd2/transactionv2/steprunner.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go

extras/nightly-container/provision.yml
Downgrade lvm2 to prevent hangs while using udev.
dmeventd was never designed to be executed inside
'container' so there are some assumption about being
there only single instance of running 'dmeventd' on
the whole host system.
=> Downgrade lvm2, disable lvmetad and dmevent in gd2 container
